openapi: 3.2.0
info:
  title: Core Instance Browser API
  version: core
tags:
- name: InstanceBrowser
paths:
  /services/api/workflow/instanceBrowsers/changes:
    get:
      tags:
      - InstanceBrowser
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges_ApiWorkflowInstanceBrowserResource'
      summary: Get services api workflow instance browsers changes
      x-summary-source: derived
      operationId: getServicesApiWorkflowInstanceBrowsersChanges
      x-operation-id-source: derived
  /services/api/workflow/instanceBrowsers/template:
    get:
      tags:
      - InstanceBrowser
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResult_ApiWorkflowInstanceBrowserResource'
      summary: Get services api workflow instance browsers template
      x-summary-source: derived
      operationId: getServicesApiWorkflowInstanceBrowsersTemplate
      x-operation-id-source: derived
  /services/api/workflow/instanceBrowsers/{id}:
    get:
      tags:
      - InstanceBrowser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: include
        in: query
        schema:
          type: string
      - name: expand
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity_ApiWorkflowInstanceBrowserResource'
      summary: Get services api workflow instance browsers by id
      x-summary-source: derived
      operationId: getServicesApiWorkflowInstanceBrowsersById
      x-operation-id-source: derived
    put:
      tags:
      - InstanceBrowser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Replace services api workflow instance browsers by id
      x-summary-source: derived
      operationId: putServicesApiWorkflowInstanceBrowsersById
      x-operation-id-source: derived
    delete:
      tags:
      - InstanceBrowser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResource'
      summary: Delete services api workflow instance browsers by id
      x-summary-source: derived
      operationId: deleteServicesApiWorkflowInstanceBrowsersById
      x-operation-id-source: derived
  /services/api/workflow/instanceBrowsers/{id}/blob/{blobMemberName}:
    get:
      tags:
      - InstanceBrowser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: blobMemberName
        in: path
        required: true
        schema:
          type: string
      - name: fileName
        in: query
        schema:
          type: string
      - name: contentType
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
      summary: Get services api workflow instance browsers by id blob by blob member name
      x-summary-source: derived
      operationId: getServicesApiWorkflowInstanceBrowsersByIdBlobByBlobMemberName
      x-operation-id-source: derived
  /services/api/workflow/instanceBrowsers:
    get:
      tags:
      - InstanceBrowser
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: order
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: includeCount
        in: query
        schema:
          type: string
      - name: includeDeleted
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection_ApiWorkflowInstanceBrowserResource'
      summary: Get services api workflow instance browsers
      x-summary-source: derived
      operationId: getServicesApiWorkflowInstanceBrowsers
      x-operation-id-source: derived
    post:
      tags:
      - InstanceBrowser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Create services api workflow instance browsers
      x-summary-source: derived
      operationId: postServicesApiWorkflowInstanceBrowsers
      x-operation-id-source: derived
components:
  schemas:
    AMCS.Core.Entity.Api.Workflow.ApiWorkflowInstanceBrowser:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tempIdentifier:
          type:
          - string
          - 'null'
        workflowInstanceId:
          type: string
          format: uuid
        workflowDefinitionId:
          type: string
          format: uuid
        providerName:
          type:
          - string
          - 'null'
        providerDescription:
          type:
          - string
          - 'null'
        definitionName:
          type:
          - string
          - 'null'
        started:
          type: string
          format: dateTime
          example: '2000-01-01 00:00:00.000'
        userContext:
          type:
          - string
          - 'null'
        status:
          type:
          - string
          - 'null'
        statusId:
          type: integer
          format: int32
      additionalProperties: false
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type:
          - string
          - 'null'
        cursor:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceChanges_ApiWorkflowInstanceBrowserResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowInstanceBrowser'
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiResourceResultEntity_ApiWorkflowInstanceBrowserResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowInstanceBrowser'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
      additionalProperties: false
    ApiResourceId:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: integer
          format: int32
      additionalProperties: false
    ApiResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
      additionalProperties: false
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - object
            - 'null'
            additionalProperties: {}
        include:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - array
            - 'null'
            items:
              type: object
              additionalProperties: {}
      additionalProperties: false
    ApiResourceResult_ApiWorkflowInstanceBrowserResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowInstanceBrowser'
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type:
          - string
          - 'null'
        associations:
          type:
          - array
          - 'null'
          items:
            type: string
        expand:
          type:
          - array
          - 'null'
          items:
            type: string
        operations:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    ApiResourceResultCollection_ApiWorkflowInstanceBrowserResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowInstanceBrowser'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
      additionalProperties: false
