openapi: 3.2.0
info:
  description: '# Getting Started


    ## Document Purpose and Scope


    The Transport Live View REST API endpoints are technically described in this document.'
  title: API Gps Data External API
  version: external
tags:
- name: ApiGpsDataExternal
paths:
  /integrator/gpsdata/changes:
    get:
      tags:
      - ApiGpsDataExternal
      summary: 'Response: API GPS Data External'
      description: '# API GPS Data Changes


        Provides a structured response for changes in GPS Data Points.'
      parameters:
      - name: Since
        in: query
        required: false
        schema:
          type: string
          format: date-time
        description: The timestamp to retrieve changes from.
      - name: Cursor
        in: query
        required: false
        schema:
          type: string
        description: A cursor for paginated results.
      responses:
        '200':
          description: Successful response with GPS data point changes.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GpsDataPointChangesResponse'
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.
      operationId: getIntegratorGpsdataChanges
      x-operation-id-source: derived
components:
  schemas:
    GpsDataPointChangesLink:
      type: object
      properties:
        Next:
          type: string
    GpsDataPointChangeResourceDto:
      type: object
      properties:
        Resource:
          $ref: '#/components/schemas/GpsDataPointChangeDto'
    GpsDataPointChangesExtra:
      type: object
      properties:
        Cursor:
          type: string
        Until:
          type: string
    GpsDataPointChangeDto:
      type: object
      properties:
        Id:
          type: string
        PlateNo:
          type: string
        Timestamp:
          type: string
          format: date-time
        Latitude:
          type: number
          format: double
        Longitude:
          type: number
          format: double
        SpeedKmh:
          type: integer
          format: int32
        TenantId:
          type: string
          format: uuid
    GpsDataPointChangesResponse:
      type: object
      properties:
        Resource:
          type: array
          items:
            $ref: '#/components/schemas/GpsDataPointChangeResourceDto'
        Extra:
          $ref: '#/components/schemas/GpsDataPointChangesExtra'
        Links:
          $ref: '#/components/schemas/GpsDataPointChangesLink'
