openapi: 3.0.1
info:
  title: Core AccessGroup TempFile API
  version: core
tags:
- name: TempFile
paths:
  /uploads:
    get:
      tags:
      - TempFile
      parameters:
      - name: id
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
    post:
      tags:
      - TempFile
      responses:
        '200':
          description: Success
    delete:
      tags:
      - TempFile
      parameters:
      - name: id
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
