openapi: 3.2.0
info:
  title: Core Authentication API
  version: core
tags:
- name: Authentication
paths:
  /services/api/login:
    post:
      tags:
      - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.Core.Entity.Api.Login.LoginDetails'
          text/json:
            schema:
              $ref: '#/components/schemas/AMCS.Core.Entity.Api.Login.LoginDetails'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AMCS.Core.Entity.Api.Login.LoginDetails'
      responses:
        '200':
          description: Success
      summary: Create services api login
      x-summary-source: derived
      operationId: postServicesApiLogin
      x-operation-id-source: derived
  /services/api/loginPageConfiguration:
    get:
      tags:
      - Authentication
      responses:
        '200':
          description: Success
      summary: Get services api login page configuration
      x-summary-source: derived
      operationId: getServicesApiLoginPageConfiguration
      x-operation-id-source: derived
  /services/api/verifyToken:
    get:
      tags:
      - Authentication
      responses:
        '200':
          description: Success
      summary: Get services api verify token
      x-summary-source: derived
      operationId: getServicesApiVerifyToken
      x-operation-id-source: derived
components:
  schemas:
    AMCS.Core.Entity.Api.Login.LoginDetails:
      type: object
      properties:
        username:
          type:
          - string
          - 'null'
        password:
          type:
          - string
          - 'null'
        stayLoggedIn:
          type: boolean
      additionalProperties: false
