openapi: 3.0.1
info:
  title: Core AccessGroup LocationDataSave API
  version: core
tags:
- name: LocationDataSave
paths:
  /udf/locationDataSaves/changes:
    get:
      tags:
      - LocationDataSave
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges[ApiUdfLocationDataSaveResource]'
  /udf/locationDataSaves/template:
    get:
      tags:
      - LocationDataSave
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResult[ApiUdfLocationDataSaveResource]'
  /udf/locationDataSaves/{id}:
    get:
      tags:
      - LocationDataSave
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: include
        in: query
        schema:
          type: string
      - name: expand
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ApiUdfLocationDataSaveResource]'
  /udf/locationDataSaves/{id}/blob/{blobMemberName}:
    get:
      tags:
      - LocationDataSave
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: blobMemberName
        in: path
        required: true
        schema:
          type: string
      - name: fileName
        in: query
        schema:
          type: string
      - name: contentType
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
  /udf/locationDataSaves:
    get:
      tags:
      - LocationDataSave
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: order
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: includeCount
        in: query
        schema:
          type: string
      - name: includeDeleted
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiUdfLocationDataSaveResource]'
components:
  schemas:
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type: string
          nullable: true
        cursor:
          type: string
          nullable: true
      additionalProperties: false
    AMCS.Data.Entity.Api.Udf.ApiUdfLocationDataSave:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type: integer
          format: int32
          nullable: true
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type: string
          format: uuid
          nullable: true
        lastChangeReasonId:
          type: integer
          format: int32
          nullable: true
        tempIdentifier:
          type: string
          nullable: true
        businessObjectName:
          type: string
          nullable: true
        components:
          type: array
          items:
            $ref: '#/components/schemas/AMCS.Data.Entity.Api.Udf.ApiUdfLocationSave'
          nullable: true
      additionalProperties: false
    AMCS.Data.Entity.Api.Udf.ApiUdfLocationSave:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type: integer
          format: int32
          nullable: true
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type: string
          format: uuid
          nullable: true
        lastChangeReasonId:
          type: integer
          format: int32
          nullable: true
        tempIdentifier:
          type: string
          nullable: true
        udFs:
          type: array
          items:
            $ref: '#/components/schemas/AMCS.Data.Entity.Api.Udf.ApiUdfSave'
          nullable: true
      additionalProperties: false
    AMCS.Data.Entity.Api.Udf.ApiUdfSave:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type: integer
          format: int32
          nullable: true
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type: string
          format: uuid
          nullable: true
        lastChangeReasonId:
          type: integer
          format: int32
          nullable: true
        tempIdentifier:
          type: string
          nullable: true
        fieldName:
          type: string
          nullable: true
        row:
          type: integer
          format: int32
        column:
          type: integer
          format: int32
      additionalProperties: false
    ApiResourceResult[ApiUdfLocationDataSaveResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Data.Entity.Api.Udf.ApiUdfLocationDataSave'
      additionalProperties: false
    ApiResourceChanges[ApiUdfLocationDataSaveResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: array
          items:
            $ref: '#/components/schemas/AMCS.Data.Entity.Api.Udf.ApiUdfLocationDataSave'
          nullable: true
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
          nullable: true
      additionalProperties: false
    ApiResourceResultCollection[ApiUdfLocationDataSaveResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: array
          items:
            $ref: '#/components/schemas/AMCS.Data.Entity.Api.Udf.ApiUdfLocationDataSave'
          nullable: true
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
          nullable: true
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties: {}
            nullable: true
          nullable: true
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties: {}
            nullable: true
          nullable: true
      additionalProperties: false
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
          nullable: true
        associations:
          type: array
          items:
            type: string
          nullable: true
        expand:
          type: array
          items:
            type: string
          nullable: true
        operations:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
    ApiResourceResultEntity[ApiUdfLocationDataSaveResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Data.Entity.Api.Udf.ApiUdfLocationDataSave'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
      additionalProperties: false
