openapi: 3.0.1
info:
  title: Core AccessGroup InventoryProductionShiftMaterialIn API
  version: core
tags:
- name: InventoryProductionShiftMaterialIn
paths:
  /mirror/imm/inventoryProductionShiftMaterialIns:
    post:
      tags:
      - InventoryProductionShiftMaterialIn
      summary: Create or update
      operationId: InventoryProductionShiftMaterialIn_Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiIntegratorInventoryProductionShiftMaterialInResource'
        required: true
        x-bodyName: null
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
  /mirror/imm/inventoryProductionShiftMaterialIns/{guid}:
    put:
      tags:
      - InventoryProductionShiftMaterialIn
      summary: Partial update
      operationId: InventoryProductionShiftMaterialIn_Update
      parameters:
      - name: guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiIntegratorInventoryProductionShiftMaterialInResource'
        required: true
        x-bodyName: null
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
components:
  schemas:
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiResourceId:
      type: object
      properties:
        resource:
          type: string
          format: uuid
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiIntegratorInventoryProductionShiftMaterialInResource:
      type: object
      properties:
        InventoryProductionShiftGuid:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
        MaterialClassGuid:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
        MaterialFinishedStateGuid:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
        TipLocationGuid:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
        Percentage:
          type: number
          format: double
        Weight:
          type: number
          format: double
        UnitCost:
          type: number
          format: double
        TotalCost:
          type: number
          format: double
        IsDeleted:
          type: boolean
        GUID:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
        isSuccess:
          type: boolean
