openapi: 3.0.1
info:
  title: Core AccessGroup CoreConfiguration API
  version: core
tags:
- name: CoreConfiguration
paths:
  /services/api/coreLoginConfiguration:
    get:
      tags:
      - CoreConfiguration
      responses:
        '200':
          description: Success
  /services/api/coreApplicationUISettings:
    get:
      tags:
      - CoreConfiguration
      responses:
        '200':
          description: Success
