openapi: 3.2.0
info:
  title: Core Configuration API
  version: core
tags:
- name: CoreConfiguration
paths:
  /services/api/coreLoginConfiguration:
    get:
      tags:
      - CoreConfiguration
      responses:
        '200':
          description: Success
      summary: Get services api core login configuration
      x-summary-source: derived
      operationId: getServicesApiCoreLoginConfiguration
      x-operation-id-source: derived
  /services/api/coreApplicationUISettings:
    get:
      tags:
      - CoreConfiguration
      responses:
        '200':
          description: Success
      summary: Get services api core application ui settings
      x-summary-source: derived
      operationId: getServicesApiCoreApplicationUISettings
      x-operation-id-source: derived
