openapi: 3.2.0
info:
  title: Core Web Hook Callback API
  version: core
tags:
- name: WebHookCallback
paths:
  /services/api/webhook/callback:
    post:
      tags:
      - WebHookCallback
      parameters:
      - name: registrationKey
        in: query
        schema:
          type: string
      - name: id
        in: query
        schema:
          type: string
      - name: action
        in: query
        schema:
          type: string
      - name: txid
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
      summary: Create services api webhook callback
      x-summary-source: derived
      operationId: postServicesApiWebhookCallback
      x-operation-id-source: derived
