openapi: 3.0.1
info:
  title: Core AccessGroup MomentTimeZoneDatabase API
  version: core
tags:
- name: MomentTimeZoneDatabase
paths:
  /momentTimeZoneDatabase:
    get:
      tags:
      - MomentTimeZoneDatabase
      responses:
        '200':
          description: Success
