openapi: 3.0.1
info:
  title: Core AccessGroup CustomerTemplate API
  version: core
tags:
- name: CustomerTemplate
paths:
  /lists/customerTemplates/{guid}:
    get:
      tags:
      - CustomerTemplate
      summary: Find with GUID
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the customer template|\r\n| Description               | The description of the customer template|\r\n| IsDeleted                 | Whether the customer template is deleted       |\r\n| BusinessTypeListItem      | The GUID and Description of the business type       |\r\n| OutletListItem            | The GUID and Description of the company outlet        |"
      operationId: CustomerTemplate_Get
      parameters:
      - name: guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ApiIntegratorCustomerTemplateResource]'
  /lists/customerTemplates:
    get:
      tags:
      - CustomerTemplate
      summary: Find with Filters
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the customer template|\r\n| Description               | The description of the customer template|\r\n| IsDeleted                 | Whether the customer template is deleted       |\r\n| BusinessTypeListItem      | The GUID and Description of the business type       |\r\n| OutletListItem            | The GUID and Description of the company outlet        |"
      operationId: CustomerTemplate_GetCollection
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: includeCount
        in: query
        schema:
          type: boolean
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiIntegratorCustomerTemplateResource]'
components:
  schemas:
    ApiIntegratorListItemResource:
      type: object
      properties:
        Description:
          type: string
        Guid:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceResultCollection[ApiIntegratorCustomerTemplateResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorCustomerTemplateResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultEntity[ApiIntegratorCustomerTemplateResource]:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/ApiIntegratorCustomerTemplateResource'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiIntegratorCustomerTemplateResource:
      type: object
      properties:
        Description:
          type: string
        IsDeleted:
          type: boolean
        BusinessTypeListItem:
          $ref: '#/components/schemas/ApiIntegratorListItemResource'
        OutletListItem:
          $ref: '#/components/schemas/ApiIntegratorListItemResource'
        GUID:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties:
                type: object
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
        associations:
          type: array
          items:
            type: string
        expand:
          type: array
          items:
            type: string
        operations:
          type: array
          items:
            type: string
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
        isSuccess:
          type: boolean
