openapi: 3.2.0
info:
  title: Core Application UI Settings API
  version: core
tags:
- name: ApplicationUISettings
paths:
  /applicationUISettings:
    get:
      tags:
      - ApplicationUISettings
      responses:
        '200':
          description: Success
      summary: Get application ui settings
      x-summary-source: derived
      operationId: getApplicationUISettings
      x-operation-id-source: derived
