openapi: 3.2.0
info:
  title: Core Plugin Install API
  version: core
tags:
- name: PluginInstall
paths:
  /plugins/PluginMetadatas:
    post:
      tags:
      - PluginInstall
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.Core.Entity.Api.Plugin.ApiPluginMetadata'
          text/json:
            schema:
              $ref: '#/components/schemas/AMCS.Core.Entity.Api.Plugin.ApiPluginMetadata'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AMCS.Core.Entity.Api.Plugin.ApiPluginMetadata'
      responses:
        '200':
          description: Success
      summary: Create plugins plugin metadatas
      x-summary-source: derived
      operationId: postPluginsPluginMetadatas
      x-operation-id-source: derived
components:
  schemas:
    AMCS.Core.Entity.Api.Plugin.ApiPluginMetadata:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tempIdentifier:
          type:
          - string
          - 'null'
        pluginMetadataId:
          type:
          - integer
          - 'null'
          format: int32
        name:
          type:
          - string
          - 'null'
        credentials:
          type:
          - string
          - 'null'
        endpoint:
          type:
          - string
          - 'null'
        dependsOnPlugins:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.Plugin.ApiPluginMetadata'
        isOptionalDependency:
          type: boolean
      additionalProperties: false
