openapi: 3.0.1
info:
  title: Core AccessGroup WorkflowActivity API
  version: core
tags:
- name: WorkflowActivity
paths:
  /services/api/usercontext:
    get:
      tags:
      - WorkflowActivity
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: userConnectionId
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
