openapi: 3.2.0
info:
  title: Core Provider API
  version: core
tags:
- name: Provider
paths:
  /services/api/workflow/providers:
    get:
      tags:
      - Provider
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: order
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: includeCount
        in: query
        schema:
          type: string
      - name: includeDeleted
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection_ApiWorkflowProviderResource'
      summary: Get services api workflow providers
      x-summary-source: derived
      operationId: getServicesApiWorkflowProviders
      x-operation-id-source: derived
components:
  schemas:
    AMCS.Data.Entity.Workflow.ApiWorkflowProvider:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tempIdentifier:
          type:
          - string
          - 'null'
        workflowProviderId:
          type:
          - integer
          - 'null'
          format: int32
        name:
          type:
          - string
          - 'null'
        systemCategory:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        endpoint:
          type:
          - string
          - 'null'
        apiVersion:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiResourceResultCollection_ApiWorkflowProviderResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Data.Entity.Workflow.ApiWorkflowProvider'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
