openapi: 3.2.0
info:
  title: Core Reverse Proxy Rule API
  version: core
tags:
- name: ReverseProxyRule
paths:
  /services/api/reverseProxyRules/changes:
    get:
      tags:
      - ReverseProxyRule
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges_ReverseProxyRuleResource'
      summary: Get services api reverse proxy rules changes
      x-summary-source: derived
      operationId: getServicesApiReverseProxyRulesChanges
      x-operation-id-source: derived
  /services/api/reverseProxyRules/template:
    get:
      tags:
      - ReverseProxyRule
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResult_ReverseProxyRuleResource'
      summary: Get services api reverse proxy rules template
      x-summary-source: derived
      operationId: getServicesApiReverseProxyRulesTemplate
      x-operation-id-source: derived
  /services/api/reverseProxyRules/{id}:
    get:
      tags:
      - ReverseProxyRule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: include
        in: query
        schema:
          type: string
      - name: expand
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity_ReverseProxyRuleResource'
      summary: Get services api reverse proxy rules by id
      x-summary-source: derived
      operationId: getServicesApiReverseProxyRulesById
      x-operation-id-source: derived
    put:
      tags:
      - ReverseProxyRule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Replace services api reverse proxy rules by id
      x-summary-source: derived
      operationId: putServicesApiReverseProxyRulesById
      x-operation-id-source: derived
    delete:
      tags:
      - ReverseProxyRule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResource'
      summary: Delete services api reverse proxy rules by id
      x-summary-source: derived
      operationId: deleteServicesApiReverseProxyRulesById
      x-operation-id-source: derived
  /services/api/reverseProxyRules/{id}/blob/{blobMemberName}:
    get:
      tags:
      - ReverseProxyRule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: blobMemberName
        in: path
        required: true
        schema:
          type: string
      - name: fileName
        in: query
        schema:
          type: string
      - name: contentType
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
      summary: Get services api reverse proxy rules by id blob by blob member name
      x-summary-source: derived
      operationId: getServicesApiReverseProxyRulesByIdBlobByBlobMemberName
      x-operation-id-source: derived
  /services/api/reverseProxyRules:
    get:
      tags:
      - ReverseProxyRule
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: order
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: includeCount
        in: query
        schema:
          type: string
      - name: includeDeleted
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection_ReverseProxyRuleResource'
      summary: Get services api reverse proxy rules
      x-summary-source: derived
      operationId: getServicesApiReverseProxyRules
      x-operation-id-source: derived
    post:
      tags:
      - ReverseProxyRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Create services api reverse proxy rules
      x-summary-source: derived
      operationId: postServicesApiReverseProxyRules
      x-operation-id-source: derived
components:
  schemas:
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type:
          - string
          - 'null'
        cursor:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceChanges_ReverseProxyRuleResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.ReverseProxyRuleEntity'
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiResourceResultEntity_ReverseProxyRuleResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.ReverseProxyRuleEntity'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
      additionalProperties: false
    ApiResourceResultCollection_ReverseProxyRuleResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.ReverseProxyRuleEntity'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
      additionalProperties: false
    ApiResourceResult_ReverseProxyRuleResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.ReverseProxyRuleEntity'
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
      additionalProperties: false
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - object
            - 'null'
            additionalProperties: {}
        include:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - array
            - 'null'
            items:
              type: object
              additionalProperties: {}
      additionalProperties: false
    ApiResourceId:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: integer
          format: int32
      additionalProperties: false
    AMCS.Core.Entity.ReverseProxyRuleEntity:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tempIdentifier:
          type:
          - string
          - 'null'
        reverseProxyRuleId:
          type:
          - integer
          - 'null'
          format: int32
        name:
          type:
          - string
          - 'null'
        systemCategory:
          type:
          - string
          - 'null'
        prefix:
          type:
          - string
          - 'null'
        target:
          type:
          - string
          - 'null'
        containerNavigationPrefix:
          type:
          - string
          - 'null'
        isIgnoreProxy:
          type: boolean
      additionalProperties: false
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type:
          - string
          - 'null'
        associations:
          type:
          - array
          - 'null'
          items:
            type: string
        expand:
          type:
          - array
          - 'null'
          items:
            type: string
        operations:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
