openapi: 3.0.1
info:
  title: Core AccessGroup UnitOfMeasure API
  version: core
tags:
- name: UnitOfMeasure
paths:
  /lists/unitOfMeasures/{guid}:
    get:
      tags:
      - UnitOfMeasure
      summary: Find with GUID
      description: "| Property| Description|\r\n| ------------------------------| ------------------------------------------------------------------------- |\r\n| GUID| The GUID associated to the unit of measure|\r\n| Description| The description of the unit of measure|\r\n| Code| The unit of measure code|\r\n| PricingBasisListItem| The GUID and description of the pricing basis (various values).|\r\n| ShortName| The unit of measure short name|\r\n| IsDeleted| Whether the unit of measure is deleted|\r\n| IsBaseUnitOfMeasurement| Defines whether unit of measure is Base Unit Of Measurement|\r\n| IsReportingUnitOfMeasurement  | Defines whether unit of measure is reporting Unit Of Measurement|\r\n| IsDefault| Defines whether unit of measure is for pricing basis|\r\n| ConversionFactor              | The conversion factor of the unit of measure|"
      operationId: UnitOfMeasure_Get
      parameters:
      - name: guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ApiIntegratorUnitOfMeasurementResource]'
  /lists/unitOfMeasures:
    get:
      tags:
      - UnitOfMeasure
      summary: Find with Filters
      description: "| Property| Description|\r\n| ------------------------------| ------------------------------------------------------------------------- |\r\n| GUID| The GUID associated to the unit of measure|\r\n| Description| The description of the unit of measure|\r\n| Code| The unit of measure code|\r\n| PricingBasisListItem| The GUID and description of the pricing basis (various values).|\r\n| ShortName| The unit of measure short name|\r\n| IsDeleted| Whether the unit of measure is deleted|\r\n| IsBaseUnitOfMeasurement| Defines whether unit of measure is Base Unit Of Measurement|\r\n| IsReportingUnitOfMeasurement  | Defines whether unit of measure is reporting Unit Of Measurement|\r\n| IsDefault| Defines whether unit of measure is for pricing basis|\r\n| ConversionFactor              | The conversion factor of the unit of measure|"
      operationId: UnitOfMeasure_GetCollection
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: includeCount
        in: query
        schema:
          type: boolean
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiIntegratorUnitOfMeasurementResource]'
components:
  schemas:
    ApiIntegratorListItemResource:
      type: object
      properties:
        Description:
          type: string
        Guid:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiResourceResultEntity[ApiIntegratorUnitOfMeasurementResource]:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/ApiIntegratorUnitOfMeasurementResource'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties:
                type: object
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
        associations:
          type: array
          items:
            type: string
        expand:
          type: array
          items:
            type: string
        operations:
          type: array
          items:
            type: string
    ApiIntegratorUnitOfMeasurementResource:
      type: object
      properties:
        Description:
          type: string
        IsDeleted:
          type: boolean
        Code:
          type: string
        PricingBasisListItem:
          $ref: '#/components/schemas/ApiIntegratorListItemResource'
        ShortName:
          type: string
        IsBaseUnitOfMeasurement:
          type: boolean
        IsReportingUnitOfMeasurement:
          type: boolean
        IsDefault:
          type: boolean
        ConversionFactor:
          type: number
          format: double
        GUID:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
        isSuccess:
          type: boolean
    ApiResourceResultCollection[ApiIntegratorUnitOfMeasurementResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorUnitOfMeasurementResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
