openapi: 3.2.0
info:
  description: '**Download Trux JSON**


    ---


    # Getting Started


    ## Document Purpose and Scope


    The VisionAI REST API endpoints are technically described in this document.'
  title: External Contamination Event API
  version: external
servers:
- url: https://o1-dev-svc-core.amcsplatform.com/
  description: AMCS VisionAI Developer Environment
security:
- cookieAuth: []
tags:
- name: ContaminationEvent
paths:
  /visionai/api/integrator/contaminationEvents/changes:
    get:
      tags:
      - ContaminationEvent
      operationId: GetContaminationEventChanges
      summary: Request list of Contamination Event changes
      description: '# Request list of Contamination Event changes


        Retrieve changes in the list of Contamination Events for all tenants, that have been made since a specific point in the history


        ## Input


        | Parameter | Description |

        | ----------------------- | -------------------------- |

        | since | Bookmark from extra.until |

        | cursor | Bookmark from extra.cursor |

        | links | N/A |


        ## Output


        | Property | Type | Description |

        | ------------------- | -------- | ---------------------------------------------------------------------------------- |

        | GUID | GUID | ID of the Contamination Event. |

        | TenantId | GUID | ID of the Tenant associated with the Contamination Event |

        | CustomerName |string| Name of the customer of the Contamination Event|

        | CompanyOutletId | GUID | ID of the Company Outlet associated with the Contamination Event |

        | OutletName | string | Name of the Company Outlet associated with the Contamination Event |

        | CustomerSiteId | GUID | ID of the Customer Site associated with the Contamination Event |

        | SiteName | string | Name of the Site associated with the Contamination Event |

        | CustomerType | string | Type of customer associated with the Contamination Event |

        | CustomerAddress | string | Address of customer associated with the Contamination Event |

        | VehicleId | GUID | ID of the Vehicle associated with the Contamination Event |

        | Latitude | double | Location of the Contamination Event |

        | Longitude | double | Location of the Contamination Event |

        | Timestamp | DateTime | Timestamp of the Contamination Event |

        | ContaminationScore | int | Degree of Contamination found |

        | GrossWeight |double|Gross weight of the Contamination Event |

        | TareWeight |double| Tare weight of the Contamination Event |

        | NetWeight |double| Net weight of the Contamination Event|

        | Seq |int|Sequence of the Contamination Event |

        | RFID | GUID | RFID of the Contamination Event |

        | WeighErrorCode | int | Weight error code of the Contamination Event |

        | Lifter |int|Lifter of the Contamination Event |

        | ContainerId |string|Conntainer Id of the Contamination Event |

        | WasteType |string|Waste type of the Contamination Event |

        | QRCodeRawText |string| Raw QR code value of the COntamination Event

        | TotalSurfaceAreaVolume |double| The total surface area of the Contamination Event

        | Materials |string| The materials detected of the Contamination Event

        | ExternalEventId |string| The external event Id of the Contamination Event

        | ImageSas |byte[]| The image SAS url of the Contamination Event expires within 24 hours

        |extra.until | string | Bookmark to put in as "since" later - appears when there are no more pages for now |

        | link.next | URI | Link to follow to get next page with changes |'
      parameters:
      - name: since
        in: query
        required: false
        schema:
          type: string
      - name: cursor
        required: false
        in: query
        schema:
          type: string
      - name: links
        required: false
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges_ApiContaminationEventExternalResource'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '501':
          $ref: '#/components/responses/NotImplemented'
        '502':
          $ref: '#/components/responses/BadGateway'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
components:
  responses:
    BadGateway:
      description: Bad Gateway - The upstream server returned an invalid response.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Temporary issue with the server. Please try again later.
            additionalProperties: false
    ServiceUnavailable:
      description: Service Unavailable - The server is currently unavailable.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Service is currently unavailable. Please try again later.
            additionalProperties: false
    BadRequest:
      description: Bad Request - Invalid input parameters.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Invalid request. Please check your input parameters.
            additionalProperties: false
    InternalServerError:
      description: Supplied properties are not valid, please try again with proper request.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Supplied properties are not valid, please try again with proper request.
            additionalProperties: false
    GatewayTimeout:
      description: Gateway Timeout - The server took too long to respond.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: The request timed out. Please try again later.
            additionalProperties: false
    NotImplemented:
      description: This feature is not implemented.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: This feature is not implemented.
            additionalProperties: false
    Forbidden:
      description: Forbidden - Access denied.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: You do not have permission to access this resource.
            additionalProperties: false
    NotFound:
      description: Not Found - The requested resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: The requested resource was not found.
            additionalProperties: false
  schemas:
    ApiResourceChanges_ApiContaminationEventExternalResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.IoT.Contamination.Api.Integrator.ContaminationEvent.ApiContaminationEventExternal'
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type:
          - string
          - 'null'
        cursor:
          type:
          - string
          - 'null'
        since:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        isSuccess:
          type: boolean
      additionalProperties: false
    AMCS.IoT.Contamination.Api.Integrator.ContaminationEvent.ApiContaminationEventExternal:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/AMCS.IoT.Contamination.Api.Integrator.ContaminationEvent.ApiContaminationEventExternalResourceItem'
      additionalProperties: false
    AMCS.IoT.Contamination.Api.Integrator.ContaminationEvent.ApiContaminationEventExternalResourceItem:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tempIdentifier:
          type:
          - string
          - 'null'
        tenantId:
          type: string
          format: uuid
        customerName:
          type:
          - string
          - 'null'
        companyOutletId:
          type:
          - string
          - 'null'
          format: uuid
        outletName:
          type:
          - string
          - 'null'
        customerSiteId:
          type:
          - string
          - 'null'
          format: uuid
        siteName:
          type:
          - string
          - 'null'
        customerType:
          type:
          - string
          - 'null'
        customerAddress:
          type:
          - string
          - 'null'
        vehicleId:
          type:
          - string
          - 'null'
          format: uuid
        vehicleReg:
          type:
          - string
          - 'null'
        latitude:
          type:
          - number
          - 'null'
          format: double
        longitude:
          type:
          - number
          - 'null'
          format: double
        timestamp:
          type: string
          format: dateTime
          example: '2000-01-01 00:00:00.000'
        contaminationScore:
          type:
          - integer
          - 'null'
          format: int32
        grossWeight:
          type:
          - number
          - 'null'
          format: double
        tareWeight:
          type:
          - number
          - 'null'
          format: double
        netWeight:
          type:
          - number
          - 'null'
          format: double
        seq:
          type:
          - integer
          - 'null'
          format: int32
        rfid:
          type:
          - string
          - 'null'
          format: uuid
        weighErrorCode:
          type:
          - integer
          - 'null'
          format: int32
        lifter:
          type:
          - integer
          - 'null'
          format: int32
        containerId:
          type:
          - string
          - 'null'
        wasteType:
          type:
          - string
          - 'null'
        qrCodeRawText:
          type:
          - string
          - 'null'
        totalSurfaceAreaVolume:
          type:
          - number
          - 'null'
          format: double
        materials:
          type:
          - string
          - 'null'
        externalEventId:
          type:
          - string
          - 'null'
        imageSas:
          type:
          - string
          - 'null'
          format: byte
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type:
          - string
          - 'null'
      additionalProperties: false
