openapi: 3.0.1
info:
  title: Core AccessGroup Company API
  version: core
tags:
- name: Company
paths:
  /lists/companies/changes:
    get:
      tags:
      - Company
      summary: Retrieve changes
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the company                               |\r\n| Description               | The description of the company                       |\r\n| AnalysisCode              | The analysis code of the company               |\r\n| CurrencyListItem          | The GUID and currency of the company (various values)                    |\r\n| IsDeleted                 | Whether the company is deleted                              |\r\n"
      operationId: Company_GetChanges
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges[ApiIntegratorCompanyResource]'
  /lists/companies/{guid}:
    get:
      tags:
      - Company
      summary: Find with GUID
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the company                               |\r\n| Description               | The description of the company                       |\r\n| AnalysisCode              | The analysis code of the company               |\r\n| CurrencyListItem          | The GUID and currency of the company (various values)                    |\r\n| IsDeleted                 | Whether the company is deleted                              |\r\n"
      operationId: Company_Get
      parameters:
      - name: guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ApiIntegratorCompanyResource]'
  /lists/companies:
    get:
      tags:
      - Company
      summary: Find with Filters
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the company                               |\r\n| Description               | The description of the company                       |\r\n| AnalysisCode              | The analysis code of the company               |\r\n| CurrencyListItem          | The GUID and currency of the company (various values)                    |\r\n| IsDeleted                 | Whether the company is deleted                              |\r\n"
      operationId: Company_GetCollection
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: includeCount
        in: query
        schema:
          type: boolean
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiIntegratorCompanyResource]'
components:
  schemas:
    ApiIntegratorListItemResource:
      type: object
      properties:
        Description:
          type: string
        Guid:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type: string
        cursor:
          type: string
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiResourceResultCollection[ApiIntegratorCompanyResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorCompanyResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
    ApiIntegratorCompanyResource:
      type: object
      properties:
        Description:
          type: string
        IsDeleted:
          type: boolean
        AnalysisCode:
          type: string
        CurrencyListItem:
          $ref: '#/components/schemas/ApiIntegratorListItemResource'
        GUID:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceChanges[ApiIntegratorCompanyResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorCompanyResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties:
                type: object
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
        associations:
          type: array
          items:
            type: string
        expand:
          type: array
          items:
            type: string
        operations:
          type: array
          items:
            type: string
    ApiResourceResultEntity[ApiIntegratorCompanyResource]:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/ApiIntegratorCompanyResource'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
        isSuccess:
          type: boolean
