openapi: 3.0.1
info:
  title: Core AccessGroup ContactType API
  version: core
tags:
- name: ContactType
paths:
  /lists/contactTypes/{guid}:
    get:
      tags:
      - ContactType
      summary: Find with GUID
      description: "| Property| Description|\r\n| --------------------------------- |---------------------------------------------------------------------- |\r\n| GUID| The GUID associated to the contact type.|\r\n| Description| The description associated to the contact type.|\r\n"
      operationId: ContactType_Get
      parameters:
      - name: guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ApiIntegratorContactTypeResource]'
  /lists/contactTypes:
    get:
      tags:
      - ContactType
      summary: Find with Filters
      description: "| Property| Description|\r\n| --------------------------------- |---------------------------------------------------------------------- |\r\n| GUID| The GUID associated to the contact type.|\r\n| Description| The description associated to the contact type.|\r\n"
      operationId: ContactType_GetCollection
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: includeCount
        in: query
        schema:
          type: boolean
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiIntegratorContactTypeResource]'
components:
  schemas:
    ApiIntegratorContactTypeResource:
      type: object
      properties:
        Description:
          type: string
        GUID:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
    ApiResourceResultCollection[ApiIntegratorContactTypeResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorContactTypeResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties:
                type: object
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
        associations:
          type: array
          items:
            type: string
        expand:
          type: array
          items:
            type: string
        operations:
          type: array
          items:
            type: string
    ApiResourceResultEntity[ApiIntegratorContactTypeResource]:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/ApiIntegratorContactTypeResource'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
        isSuccess:
          type: boolean
