openapi: 3.2.0
info:
  description: '# Getting Started


    ## Document Purpose and Scope


    The Scale REST API endpoints are technically described in this document.'
  title: Scale REST Weight Blob API
  version: '9.1'
servers:
- url: http://{env}-svc-core.amcsplatform.com/scale/api/
tags:
- name: WeightBlob
paths:
  /integrator/weightBlobs:
    post:
      description: '| Property | Description | Required |

        |-------------------------------|-------------------------------------------|-----------|

        | WeightId | The weight Id (Guid). | Yes |

        | BlobURL | The blob url of the picture. | Yes |


        ## Extra validations


        | Condition | Error message |

        | --------- | ------------- |

        | Both WeightId and BlobURL property must have a value. |'
      operationId: WeightBlob_Create
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Create or update
      tags:
      - WeightBlob
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
        required: true
components:
  schemas:
    ApiResourceStatus:
      type: object
      properties:
        id:
          format: int32
          type: integer
        isSuccess:
          type: boolean
    ApiResourceId:
      type: object
      properties:
        resource:
          format: int32
          type: integer
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
