openapi: 3.0.1
info:
  title: Core AccessGroup PluginConfiguration API
  version: core
tags:
- name: PluginConfiguration
paths:
  /.well-known/amcs-plugin-configuration:
    get:
      tags:
      - PluginConfiguration
      responses:
        '200':
          description: Success
