openapi: 3.0.1
info:
  title: Core AccessGroup ContainerCategory API
  version: core
tags:
- name: ContainerCategory
paths:
  /lists/containerCategories/{guid}:
    get:
      tags:
      - ContainerCategory
      summary: Find with GUID
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the container category                            |\r\n| Description               | The description of the container category                                |\r\n| AnalysisCode              | The analysis code of the container category                              |\r\n| IsDeleted                 | Whether the container category is deleted                |\r\n"
      operationId: ContainerCategory_Get
      parameters:
      - name: guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ApiIntegratorContainerCategoryResource]'
  /lists/containerCategories:
    get:
      tags:
      - ContainerCategory
      summary: Find with Filters
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the container category                            |\r\n| Description               | The description of the container category                                |\r\n| AnalysisCode              | The analysis code of the container category                              |\r\n| IsDeleted                 | Whether the container category is deleted                |\r\n"
      operationId: ContainerCategory_GetCollection
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: includeCount
        in: query
        schema:
          type: boolean
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiIntegratorContainerCategoryResource]'
components:
  schemas:
    ApiResourceResultCollection[ApiIntegratorContainerCategoryResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorContainerCategoryResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiIntegratorContainerCategoryResource:
      type: object
      properties:
        Description:
          type: string
        IsDeleted:
          type: boolean
        AnalysisCode:
          type: string
        GUID:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
    ApiResourceResultEntity[ApiIntegratorContainerCategoryResource]:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/ApiIntegratorContainerCategoryResource'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties:
                type: object
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
        associations:
          type: array
          items:
            type: string
        expand:
          type: array
          items:
            type: string
        operations:
          type: array
          items:
            type: string
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
        isSuccess:
          type: boolean
