openapi: 3.2.0
info:
  title: Core Workflow Provider Web Hook API
  version: core
tags:
- name: WorkflowProviderWebHook
paths:
  /web-hook/workflow-provider/callback:
    post:
      tags:
      - WorkflowProviderWebHook
      parameters:
      - name: registrationKey
        in: query
        schema:
          type: string
      - name: id
        in: query
        schema:
          type: string
      - name: action
        in: query
        schema:
          type: string
      - name: txid
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
      summary: Create web hook workflow provider callback
      x-summary-source: derived
      operationId: postWebHookWorkflowProviderCallback
      x-operation-id-source: derived
  /web-hook/workflow-provider/delete-schedule:
    post:
      tags:
      - WorkflowProviderWebHook
      parameters:
      - name: id
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
      summary: Create web hook workflow provider delete schedule
      x-summary-source: derived
      operationId: postWebHookWorkflowProviderDeleteSchedule
      x-operation-id-source: derived
  /services/api/workflow/workflowProviderWebHooks/changes:
    get:
      tags:
      - WorkflowProviderWebHook
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges_ApiWorkflowProviderWebHookResource'
      summary: Get services api workflow workflow provider web hooks changes
      x-summary-source: derived
      operationId: getServicesApiWorkflowWorkflowProviderWebHooksChanges
      x-operation-id-source: derived
  /services/api/workflow/workflowProviderWebHooks/template:
    get:
      tags:
      - WorkflowProviderWebHook
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResult_ApiWorkflowProviderWebHookResource'
      summary: Get services api workflow workflow provider web hooks template
      x-summary-source: derived
      operationId: getServicesApiWorkflowWorkflowProviderWebHooksTemplate
      x-operation-id-source: derived
  /services/api/workflow/workflowProviderWebHooks/{id}:
    get:
      tags:
      - WorkflowProviderWebHook
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: include
        in: query
        schema:
          type: string
      - name: expand
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity_ApiWorkflowProviderWebHookResource'
      summary: Get services api workflow workflow provider web hooks by id
      x-summary-source: derived
      operationId: getServicesApiWorkflowWorkflowProviderWebHooksById
      x-operation-id-source: derived
    put:
      tags:
      - WorkflowProviderWebHook
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Replace services api workflow workflow provider web hooks by id
      x-summary-source: derived
      operationId: putServicesApiWorkflowWorkflowProviderWebHooksById
      x-operation-id-source: derived
    delete:
      tags:
      - WorkflowProviderWebHook
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResource'
      summary: Delete services api workflow workflow provider web hooks by id
      x-summary-source: derived
      operationId: deleteServicesApiWorkflowWorkflowProviderWebHooksById
      x-operation-id-source: derived
  /services/api/workflow/workflowProviderWebHooks/{id}/blob/{blobMemberName}:
    get:
      tags:
      - WorkflowProviderWebHook
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: blobMemberName
        in: path
        required: true
        schema:
          type: string
      - name: fileName
        in: query
        schema:
          type: string
      - name: contentType
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
      summary: Get services api workflow workflow provider web hooks by id blob by blob member…
      x-summary-source: derived
      operationId: getServicesApiWorkflowWorkflowProviderWebHooksByIdBlobByBlobMemberName
      x-operation-id-source: derived
  /services/api/workflow/workflowProviderWebHooks:
    get:
      tags:
      - WorkflowProviderWebHook
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: order
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: includeCount
        in: query
        schema:
          type: string
      - name: includeDeleted
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection_ApiWorkflowProviderWebHookResource'
      summary: Get services api workflow workflow provider web hooks
      x-summary-source: derived
      operationId: getServicesApiWorkflowWorkflowProviderWebHooks
      x-operation-id-source: derived
    post:
      tags:
      - WorkflowProviderWebHook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Create services api workflow workflow provider web hooks
      x-summary-source: derived
      operationId: postServicesApiWorkflowWorkflowProviderWebHooks
      x-operation-id-source: derived
components:
  schemas:
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type:
          - string
          - 'null'
        cursor:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiResourceResult_ApiWorkflowProviderWebHookResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowProviderWebHook'
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceResultEntity_ApiWorkflowProviderWebHookResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowProviderWebHook'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
      additionalProperties: false
    AMCS.Core.Entity.Api.Workflow.ApiWorkflowProviderWebHook:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tempIdentifier:
          type:
          - string
          - 'null'
        workflowProviderWebHookId:
          type:
          - integer
          - 'null'
          format: int32
        workflowProviderId:
          type: integer
          format: int32
        workflowDefinitionId:
          type: string
          format: uuid
        triggerObjectName:
          type:
          - string
          - 'null'
        triggerEventType:
          type: integer
          format: int32
        triggerEventFormat:
          type: integer
          format: int32
        triggerEventFilter:
          type:
          - string
          - 'null'
        triggerEventTypeDescriptions:
          type:
          - array
          - 'null'
          items:
            type: string
          readOnly: true
      additionalProperties: false
    ApiResourceChanges_ApiWorkflowProviderWebHookResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowProviderWebHook'
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
    ApiResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
      additionalProperties: false
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - object
            - 'null'
            additionalProperties: {}
        include:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - array
            - 'null'
            items:
              type: object
              additionalProperties: {}
      additionalProperties: false
    ApiResourceResultCollection_ApiWorkflowProviderWebHookResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowProviderWebHook'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
      additionalProperties: false
    ApiResourceId:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: integer
          format: int32
      additionalProperties: false
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type:
          - string
          - 'null'
        associations:
          type:
          - array
          - 'null'
          items:
            type: string
        expand:
          type:
          - array
          - 'null'
          items:
            type: string
        operations:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
