openapi: 3.0.1
info:
  title: Core AccessGroup AuthStatus API
  version: core
tags:
- name: AuthStatus
paths:
  /authStatus:
    get:
      tags:
      - AuthStatus
      responses:
        '200':
          description: Success
