openapi: 3.0.1
info:
  title: Core AccessGroup EmbeddedBIConfiguration API
  version: core
tags:
- name: EmbeddedBIConfiguration
paths:
  /plugin/embeddedbiconfiguration:
    post:
      tags:
      - EmbeddedBIConfiguration
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
  /services/api/embeddedbiconfiguration:
    get:
      tags:
      - EmbeddedBIConfiguration
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
