openapi: 3.0.1
info:
  title: Core AccessGroup MasterAccount API
  version: core
tags:
- name: MasterAccount
paths:
  /accounting/masterAccounts/changes:
    get:
      tags:
      - MasterAccount
      summary: Retrieve changes
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the master account.                               |\r\n| Name                      | The master account's name.                                               |\r\n| ARAccountCode             | The account code used for accounts receivable.                           |\r\n| APAccountCode             | The account code used for accounts payable.                              |\r\n| CurrencyListItem          | The GUID and currency of the master account (various values).            |\r\n"
      operationId: MasterAccount_GetChanges
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges[ApiIntegratorMasterAccountResource]'
  /accounting/masterAccounts/{guid}:
    get:
      tags:
      - MasterAccount
      summary: Find with GUID
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the master account.                               |\r\n| Name                      | The master account's name.                                               |\r\n| ARAccountCode             | The account code used for accounts receivable.                           |\r\n| APAccountCode             | The account code used for accounts payable.                              |\r\n| CurrencyListItem          | The GUID and currency of the master account (various values).            |\r\n"
      operationId: MasterAccount_Get
      parameters:
      - name: guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ApiIntegratorMasterAccountResource]'
    put:
      tags:
      - MasterAccount
      summary: Partial update
      description: "| Property                  | Description                                                              | Required |\r\n| ------------------------- | ------------------------------------------------------------------------ | -------- |\r\n| GUID                      | The GUID associated to the master account.                               | No |\r\n| Name                      | The master account's name.                                               | Yes |\r\n| ARAccountCode             | The account code used for accounts receivable.                           | Yes |\r\n| APAccountCode             | The account code used for accounts payable.                              | No |\r\n| CurrencyListItem          | The GUID and currency of the master account (various values).            | No |\r\n\r\n**Extra validations**\r\n\r\n| Condition | Error message |\r\n| --------- | ------------- |\r\n| ARAccountCode is not unique | Failed to save. Entity already exists with arAccountCode of {value of ARAccountCode} |\r\n|If the provided CurrencyListItem.Guid belongs to a deleted currency | The provided CurrencyListItem is deleted. Could not update the resource. Please check the relevant list end point for the available options. |\r\n"
      operationId: MasterAccount_Update
      parameters:
      - name: guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiIntegratorMasterAccountResource'
        required: true
        x-bodyName: null
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
  /accounting/masterAccounts:
    get:
      tags:
      - MasterAccount
      summary: Find with Filters
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the master account.                               |\r\n| Name                      | The master account's name.                                               |\r\n| ARAccountCode             | The account code used for accounts receivable.                           |\r\n| APAccountCode             | The account code used for accounts payable.                              |\r\n| CurrencyListItem          | The GUID and currency of the master account (various values).            |\r\n"
      operationId: MasterAccount_GetCollection
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: includeCount
        in: query
        schema:
          type: boolean
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiIntegratorMasterAccountResource]'
    post:
      tags:
      - MasterAccount
      summary: Create or update
      description: "| Property                  | Description                                                              | Required |\r\n| ------------------------- | ------------------------------------------------------------------------ | -------- |\r\n| GUID                      | The GUID associated to the master account.                               | No |\r\n| Name                      | The master account's name.                                               | Yes |\r\n| ARAccountCode             | The account code used for accounts receivable.                           | Yes |\r\n| APAccountCode             | The account code used for accounts payable.                              | No |\r\n| CurrencyListItem          | The GUID and currency of the master account (various values).            | No |\r\n\r\n**Extra validations**\r\n\r\n| Condition | Error message |\r\n| --------- | ------------- |\r\n| ARAccountCode is not unique | Failed to save. Entity already exists with arAccountCode of {value of ARAccountCode} |\r\n|If the provided CurrencyListItem.Guid belongs to a deleted currency | The provided CurrencyListItem is deleted. Could not update the resource. Please check the relevant list end point for the available options. |\r\n"
      operationId: MasterAccount_Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiIntegratorMasterAccountResource'
        required: true
        x-bodyName: null
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
components:
  schemas:
    ApiIntegratorListItemResource:
      type: object
      properties:
        Description:
          type: string
        Guid:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type: string
        cursor:
          type: string
    ApiResourceId:
      type: object
      properties:
        resource:
          type: string
          format: uuid
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiIntegratorMasterAccountResource:
      type: object
      properties:
        Name:
          type: string
        ARAccountCode:
          type: string
        APAccountCode:
          type: string
        CurrencyListItem:
          $ref: '#/components/schemas/ApiIntegratorListItemResource'
        GUID:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
    ApiResourceResultCollection[ApiIntegratorMasterAccountResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorMasterAccountResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties:
                type: object
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
        associations:
          type: array
          items:
            type: string
        expand:
          type: array
          items:
            type: string
        operations:
          type: array
          items:
            type: string
    ApiResourceChanges[ApiIntegratorMasterAccountResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorMasterAccountResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultEntity[ApiIntegratorMasterAccountResource]:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/ApiIntegratorMasterAccountResource'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
        isSuccess:
          type: boolean
