openapi: 3.0.1
info:
  title: Core AccessGroup PluginMetadataRegistry API
  version: core
tags:
- name: PluginMetadataRegistry
paths:
  /metadata/{type}.xml:
    get:
      tags:
      - PluginMetadataRegistry
      parameters:
      - name: type
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
