openapi: 3.0.1
info:
  title: Core AccessGroup WorkCenterIcon API
  version: core
tags:
- name: WorkCenterIcon
paths:
  /services/api/workcentericons:
    get:
      tags:
      - WorkCenterIcon
      responses:
        '200':
          description: Success
