openapi: 3.0.1
info:
  title: Core AccessGroup ContainerApplications API
  version: core
tags:
- name: ContainerApplications
paths:
  /services/api/apps/logout:
    get:
      tags:
      - ContainerApplications
      responses:
        '200':
          description: Success
