openapi: 3.2.0
info:
  title: Core Plugin Metadata Exchange API
  version: core
tags:
- name: PluginMetadataExchange
paths:
  /plugin/mex:
    post:
      tags:
      - PluginMetadataExchange
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.IPluginAction'
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.IPluginAction'
          text/json:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.IPluginAction'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.IPluginAction'
      responses:
        '200':
          description: Success
      summary: Create plugin mex
      x-summary-source: derived
      operationId: postPluginMex
      x-operation-id-source: derived
components:
  schemas:
    AMCS.PluginData.Data.IPluginAction:
      type: object
      additionalProperties: false
