openapi: 3.2.0
info:
  title: Core Embedded BI Configuration API
  version: core
tags:
- name: EmbeddedBIConfiguration
paths:
  /plugin/embeddedbiconfiguration:
    post:
      tags:
      - EmbeddedBIConfiguration
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
      summary: Create plugin embeddedbiconfiguration
      x-summary-source: derived
      operationId: postPluginEmbeddedbiconfiguration
      x-operation-id-source: derived
  /services/api/embeddedbiconfiguration:
    get:
      tags:
      - EmbeddedBIConfiguration
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
      summary: Get services api embeddedbiconfiguration
      x-summary-source: derived
      operationId: getServicesApiEmbeddedbiconfiguration
      x-operation-id-source: derived
