openapi: 3.2.0
info:
  description: '**Download Trux JSON**


    ---


    # Getting Started


    ## Document Purpose and Scope


    The VisionAI REST API endpoints are technically described in this document.'
  title: External Asset API
  version: external
servers:
- url: https://o1-dev-svc-core.amcsplatform.com/
  description: AMCS VisionAI Developer Environment
security:
- cookieAuth: []
tags:
- name: Asset
paths:
  /visionai/api/integrator/assets:
    post:
      tags:
      - Asset
      summary: Create or Update an Asset (Vehicle)
      description: '# Create or Update an Asset (Vehicle)


        | Parameter | Type | Description |

        |--------------|--------|-----------------------------------------------------------------|

        | AssetId | GUID | ID of the Asset |

        | AssetName | string | Display name (vehicle registration plate) |

        | AssetType | string | Front Loader, Side Loader, Rear End Loader |

        | OutletId | GUID | ID of the Company Outlet associated with the Asset |

        | CompanyCode | string | Company code associated with the Asset |

        | IsDeleted | bool | Asset is no longer in use |


        ## Sample API Requests


        ```

        {

        "AssetId": "B3E43C4D-BC76-4E59-9E2E-25BC33EA2EC4",

        "AssetName": "VEH 001",

        "AssetType": "Front Loader",

        "OutletId": "2FAD788D-A748-4520-9120-923DA1E42942",

        "CompanyCode": "Trux Company 1",

        "IsDeleted": false

        }

        ```


        ## Sample API Response

        ```

        {

        "resource" : "B3E43C4D-BC76-4E59-9E2E-25BC33EA2EC4"

        }'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.IoT.Contamination.Api.Integrator.Asset.ApiAsset'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiauthTokens500Error'
        '501':
          $ref: '#/components/responses/NotImplemented'
        '502':
          $ref: '#/components/responses/BadGateway'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
      operationId: postVisionaiApiIntegratorAssets
      x-operation-id-source: derived
components:
  responses:
    BadGateway:
      description: Bad Gateway - The upstream server returned an invalid response.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Temporary issue with the server. Please try again later.
            additionalProperties: false
    ServiceUnavailable:
      description: Service Unavailable - The server is currently unavailable.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Service is currently unavailable. Please try again later.
            additionalProperties: false
    BadRequest:
      description: Bad Request - Invalid input parameters.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Invalid request. Please check your input parameters.
            additionalProperties: false
    GatewayTimeout:
      description: Gateway Timeout - The server took too long to respond.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: The request timed out. Please try again later.
            additionalProperties: false
    NotImplemented:
      description: This feature is not implemented.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: This feature is not implemented.
            additionalProperties: false
    Forbidden:
      description: Forbidden - Access denied.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: You do not have permission to access this resource.
            additionalProperties: false
    NotFound:
      description: Not Found - The requested resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: The requested resource was not found.
            additionalProperties: false
  schemas:
    ApiResourceStatus:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiauthTokens500Error:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        stackTrace:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type:
          - string
          - 'null'
      additionalProperties: false
    AMCS.IoT.Contamination.Api.Integrator.Asset.ApiAsset:
      type: object
      properties:
        assetId:
          type:
          - string
          - 'null'
          format: uuid
        assetName:
          type:
          - string
          - 'null'
        assetType:
          type:
          - string
          - 'null'
        outletId:
          type:
          - string
          - 'null'
          format: uuid
        companyCode:
          type:
          - string
          - 'null'
        isDeleted:
          type: boolean
      additionalProperties: false
    ApiResourceId:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: guid
      additionalProperties: false
