openapi: 3.2.0
info:
  description: '# Getting Started


    ## Document Purpose and Scope


    The Scale REST API endpoints are technically described in this document.'
  title: Scale REST Picture API
  version: '9.1'
servers:
- url: http://{env}-svc-core.amcsplatform.com/scale/api/
tags:
- name: Picture
paths:
  /integrator/pictures:
    post:
      tags:
      - Picture
      summary: Create or update
      description: '| Property | Description | Required |

        |---------------------------------------|-----------------------------------------------|-----------|

        | DateTime | The date and time of the picture. | Yes |

        | Description | The description of the picture. | No |

        | RelatedVehicleReg | The related vehicle reg. | No |

        | Base64Picture | The Base64Picture blob hash of the picture. | Yes |

        | RelatedWeighingGuid | The weighing guid. | No |

        | IsAnpr | The Anpr picture type. | No |

        | CompanyOutletGuid | The CompanyOutlet guid. | No |

        | SubscriberGuid | The Subscriber guid. | Yes |


        ## Extra validations


        | Condition | Error message |

        |-----------|---------------|

        | If RelatedVehicleReg and RelatedWeighingGuid are both null | Either RelatedVehicleReg or RelatedWeighingGuid property must have a value. |

        | If no Weighing is found associated to the ANPR data | Weighing not found for this ANPR data. |

        | If Subscriber isnt subscribed to Outlet | Subscriber isnt subscribed to Outlet. |

        | If no Outlets were found for Subscriber | No Outlets were found for Subscriber. |'
      operationId: Picture_Create
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
        required: true
components:
  schemas:
    ApiResourceStatus:
      type: object
      properties:
        id:
          format: int32
          type: integer
        isSuccess:
          type: boolean
    ApiResourceId:
      type: object
      properties:
        resource:
          format: int32
          type: integer
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
