openapi: 3.0.1
info:
  title: Core AccessGroup MunicipalFunctionalId API
  version: core
tags:
- name: MunicipalFunctionalId
paths:
  /municipal/municipalFunctionalIds:
    get:
      tags:
      - MunicipalFunctionalId
      summary: Find with Filters
      operationId: MunicipalFunctionalId_GetCollection
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: includeCount
        in: query
        schema:
          type: boolean
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiIntegratorMunicipalFunctionalIdResource]'
components:
  schemas:
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
    ApiIntegratorMunicipalFunctionalIdResource:
      type: object
      properties:
        Postcode:
          type: string
        HouseNumber:
          type: string
        Address1:
          type: string
        Address2:
          type: string
        CustomerName:
          type: string
        Address3:
          type: string
        Address4:
          type: string
        Address5:
          type: string
        Address6:
          type: string
        Address7:
          type: string
        Address8:
          type: string
        Address9:
          type: string
        GUID:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
        isSuccess:
          type: boolean
    ApiResourceResultCollection[ApiIntegratorMunicipalFunctionalIdResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorMunicipalFunctionalIdResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
