openapi: 3.2.0
info:
  title: Core Business Object Lookup API
  version: core
tags:
- name: BusinessObjectLookup
paths:
  /udf/businessObjectLookups/changes:
    get:
      tags:
      - BusinessObjectLookup
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges_ApiUdfBusinessObjectLookupResource'
      summary: Get udf business object lookups changes
      x-summary-source: derived
      operationId: getUdfBusinessObjectLookupsChanges
      x-operation-id-source: derived
  /udf/businessObjectLookups/template:
    get:
      tags:
      - BusinessObjectLookup
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResult_ApiUdfBusinessObjectLookupResource'
      summary: Get udf business object lookups template
      x-summary-source: derived
      operationId: getUdfBusinessObjectLookupsTemplate
      x-operation-id-source: derived
  /udf/businessObjectLookups/{id}:
    get:
      tags:
      - BusinessObjectLookup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: include
        in: query
        schema:
          type: string
      - name: expand
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity_ApiUdfBusinessObjectLookupResource'
      summary: Get udf business object lookups by id
      x-summary-source: derived
      operationId: getUdfBusinessObjectLookupsById
      x-operation-id-source: derived
  /udf/businessObjectLookups/{id}/blob/{blobMemberName}:
    get:
      tags:
      - BusinessObjectLookup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: blobMemberName
        in: path
        required: true
        schema:
          type: string
      - name: fileName
        in: query
        schema:
          type: string
      - name: contentType
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
      summary: Get udf business object lookups by id blob by blob member name
      x-summary-source: derived
      operationId: getUdfBusinessObjectLookupsByIdBlobByBlobMemberName
      x-operation-id-source: derived
  /udf/businessObjectLookups:
    get:
      tags:
      - BusinessObjectLookup
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: order
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: includeCount
        in: query
        schema:
          type: string
      - name: includeDeleted
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection_ApiUdfBusinessObjectLookupResource'
      summary: Get udf business object lookups
      x-summary-source: derived
      operationId: getUdfBusinessObjectLookups
      x-operation-id-source: derived
components:
  schemas:
    ApiResourceResultEntity_ApiUdfBusinessObjectLookupResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Data.Entity.Api.Udf.ApiUdfBusinessObjectLookup'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
      additionalProperties: false
    ApiResourceResultCollection_ApiUdfBusinessObjectLookupResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Data.Entity.Api.Udf.ApiUdfBusinessObjectLookup'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
      additionalProperties: false
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type:
          - string
          - 'null'
        cursor:
          type:
          - string
          - 'null'
      additionalProperties: false
    AMCS.Data.Entity.Api.Udf.ApiUdfBusinessObjectLookup:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tempIdentifier:
          type:
          - string
          - 'null'
        businessObjectName:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiResourceResult_ApiUdfBusinessObjectLookupResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Data.Entity.Api.Udf.ApiUdfBusinessObjectLookup'
      additionalProperties: false
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - object
            - 'null'
            additionalProperties: {}
        include:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - array
            - 'null'
            items:
              type: object
              additionalProperties: {}
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type:
          - string
          - 'null'
        associations:
          type:
          - array
          - 'null'
          items:
            type: string
        expand:
          type:
          - array
          - 'null'
          items:
            type: string
        operations:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    ApiResourceChanges_ApiUdfBusinessObjectLookupResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Data.Entity.Api.Udf.ApiUdfBusinessObjectLookup'
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
