openapi: 3.2.0
info:
  title: Core Comms Server Sync Status API
  version: core
tags:
- name: CommsServerSyncStatus
paths:
  /commsServerSyncStatus:
    get:
      tags:
      - CommsServerSyncStatus
      responses:
        '200':
          description: Success
      summary: Get comms server sync status
      x-summary-source: derived
      operationId: getCommsServerSyncStatus
      x-operation-id-source: derived
