openapi: 3.2.0
info:
  description: '# Getting Started


    ## Document Purpose and Scope


    The Transport Live View REST API endpoints are technically described in this document.'
  title: External API Gps Trail Export Service API
  version: external
tags:
- name: ApiGpsTrailExportService
paths:
  /integrator/gpsTrail:
    post:
      tags:
      - ApiGpsTrailExportService
      summary: Get list of Vehicle Gps Trails
      description: '# Get list of Vehicle Gps Trail


        ## Input

        | Parameter | Type | Description |

        | ------------------- | -------- | ---------------------------------------------------------------------------------- |

        | AssetName | string | Vehicle Registration Plate No |

        | DateFrom | DateTime | Timestamp when the start date of the gps trail to be extracted |

        | DateTo | DateTime | Timestamp when the end date of the gps trail to be extracted |


        ## Sample API Requests


        ```

        {

        "AssetName": "M879 EUS",

        "DateFrom": "2024-06-28",

        "DateTo": ""2024-06-30"

        }

        ```


        ## Output

        | Property | Type | Description |

        | ------------------- | -------- | ---------------------------------------------------------------------------------- |

        | AssetName | string | Vehicle Registration Plate No |

        | Timestamp | DateTime | Timestamp of the asset |

        | Lat | DateTime | Latitude where the asset at that point |

        | Lon | DateTime | Longitude where the asset at that point |'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.MapBasedAlerting.Server.Api.Integrator.ApiGpsTrailExportService.ApiGpsTrailExportResponse'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCS.MapBasedAlerting.Server.Api.Integrator.ApiGpsTrailExportService.ApiGpsTrailExportResponse'
      operationId: postIntegratorGpsTrail
      x-operation-id-source: derived
components:
  schemas:
    AMCS.MapBasedAlerting.Server.Api.Integrator.ApiGpsTrailExportService.ApiGpsTrailExportResponse:
      type: object
      properties:
        assetName:
          type:
          - string
          - 'null'
        gpsTrail:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.MapBasedAlerting.Server.Api.Integrator.ApiGpsTrailService.ApiGpsPoint'
      additionalProperties: false
    AMCS.MapBasedAlerting.Server.Api.Integrator.ApiGpsTrailService.ApiGpsPoint:
      type: object
      properties:
        timestamp:
          type: string
          format: dateTime
          example: '2000-01-01 00:00:00.000'
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double
      additionalProperties: false
