openapi: 3.2.0
info:
  description: '**Download Trux JSON**


    ---


    # Getting Started


    ## Document Purpose and Scope


    The VisionAI REST API endpoints are technically described in this document.'
  title: External Overfilled Container Event API
  version: external
servers:
- url: https://o1-dev-svc-core.amcsplatform.com/
  description: AMCS VisionAI Developer Environment
security:
- cookieAuth: []
tags:
- name: OverfilledContainerEvent
paths:
  /visionai/api/integrator/overfilledContainerEvents/changes:
    get:
      tags:
      - OverfilledContainerEvent
      operationId: GetOverfilledContainerEventChanges
      summary: Request list of Overfilled Container Event changes
      description: '# Request list of Overfilled Container Event changes


        Retrieve changes in the list of Overfilled Container Events for all tenants, that have been made since a specific point in the history


        ## Input


        | Parameter | Description |

        | ----------------------- | -------------------------- |

        | since | Bookmark from extra.until |

        | cursor | Bookmark from extra.cursor |

        | links | N/A |


        ## Output


        | Property | Type | Description |

        | --------------------- | -------- | ---------------------------------------------------------------------------------- |

        | GUID | GUID | ID of the Overfilled Container Event. |

        | TenantId | GUID | ID of the Tenant associated with the Overfilled Container Event |

        | CustomerName | string | Name of the Customer with Overfilled Container Event |

        | CompanyOutletId | GUID | ID of the Company Outlet associated with the Overfilled Container Event |

        | OutletName | string | Name of the Company Outlet associated with the Overfilled Container Event |

        | CustomerSiteId | GUID | ID of the Customer Site associated with the Overfilled Container Event |

        | SiteName | string | Name of the Site associated with the Overfilled Container Event |

        | CustomerType | string | Type of Customer associated withe Overfilled Container Event |

        | CustomerAddress | string | Address of the Customer associated withe Overfilled Container Event |

        | VehicleId | GUID | ID of the Vehicle associated with the Overfilled Container Event |

        | VehicleReg | string | Vehicle Registration associated with the Overfilled Container Event |

        | Latitude | double | Geographic coordinate of the Overfilled Container Event |

        | Longitude | double | Geographic coordinate of the Overfilled Container Event |

        | Timestamp | DateTime | Timestamp of the Overfilled Container Event |

        | GrossWeight | double | Gross weight of the Overfilled Container Event |

        | TareWeight | double | Tare weight of the Overfilled Container Event |

        | NetWeight | double | Net weight of the Overfilled Container Event |

        | Seq | int | Sequence of the Overfilled Container Event |

        | RFID | GUID | RFID of the Overfilled Container Event |

        | WeighErrorCode | int | Weight error code of the Overfilled Container Event |

        | ContainerId | string | ContainerId of the Overfilled Container Event |

        | WasteType | string | Waste type of the Overfilled Container Event |

        | QRCodeRawText | string | QRCode raw text of the Overfilled Container Event |

        |ExternalEventId | string | The external event id of the Overfilled Container Event |

        | ImageSas |byte[]| The image SAS url of the Overfilled Event expires within 24 hours

        | extra.until | string | Bookmark to put in as "since" later - appears when there are no more pages for now |

        | link.next | URI | Link to follow to get next page with changes |'
      parameters:
      - name: since
        required: false
        in: query
        schema:
          type: string
      - name: cursor
        required: false
        in: query
        schema:
          type: string
      - name: links
        required: false
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges_ApiOverfilledContainerEventExternalResource'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '501':
          $ref: '#/components/responses/NotImplemented'
        '502':
          $ref: '#/components/responses/BadGateway'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
components:
  responses:
    BadGateway:
      description: Bad Gateway - The upstream server returned an invalid response.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Temporary issue with the server. Please try again later.
            additionalProperties: false
    ServiceUnavailable:
      description: Service Unavailable - The server is currently unavailable.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Service is currently unavailable. Please try again later.
            additionalProperties: false
    BadRequest:
      description: Bad Request - Invalid input parameters.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Invalid request. Please check your input parameters.
            additionalProperties: false
    InternalServerError:
      description: Supplied properties are not valid, please try again with proper request.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Supplied properties are not valid, please try again with proper request.
            additionalProperties: false
    GatewayTimeout:
      description: Gateway Timeout - The server took too long to respond.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: The request timed out. Please try again later.
            additionalProperties: false
    NotImplemented:
      description: This feature is not implemented.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: This feature is not implemented.
            additionalProperties: false
    Forbidden:
      description: Forbidden - Access denied.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: You do not have permission to access this resource.
            additionalProperties: false
    NotFound:
      description: Not Found - The requested resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: The requested resource was not found.
            additionalProperties: false
  schemas:
    AMCS.IoT.Contamination.Api.Integrator.OverfilledContainerEvent.ApiOverfilledContainerEventExternalResourceItem:
      type: object
      properties:
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tenantId:
          type: string
          format: uuid
        customerName:
          type:
          - string
          - 'null'
        companyOutletId:
          type:
          - string
          - 'null'
          format: uuid
        outletName:
          type:
          - string
          - 'null'
        customerSiteId:
          type:
          - string
          - 'null'
          format: uuid
        siteName:
          type:
          - string
          - 'null'
        customerType:
          type:
          - string
          - 'null'
        customerAddress:
          type:
          - string
          - 'null'
        vehicleId:
          type:
          - string
          - 'null'
          format: uuid
        vehicleReg:
          type:
          - string
          - 'null'
        latitude:
          type:
          - number
          - 'null'
          format: double
        longitude:
          type:
          - number
          - 'null'
          format: double
        timestamp:
          type: string
          format: dateTime
          example: '2000-01-01 00:00:00.000'
        grossWeight:
          type:
          - number
          - 'null'
          format: double
        tareWeight:
          type:
          - number
          - 'null'
          format: double
        netWeight:
          type:
          - number
          - 'null'
          format: double
        seq:
          type:
          - integer
          - 'null'
          format: int32
        rfid:
          type:
          - string
          - 'null'
          format: uuid
        weighErrorCode:
          type:
          - integer
          - 'null'
          format: int32
        containerId:
          type:
          - string
          - 'null'
        wasteType:
          type:
          - string
          - 'null'
        qrCodeRawText:
          type:
          - string
          - 'null'
        totalSurfaceAreaVolume:
          type:
          - number
          - 'null'
          format: double
        materials:
          type:
          - string
          - 'null'
        externalEventId:
          type:
          - string
          - 'null'
        imageSas:
          type:
          - string
          - 'null'
          format: byte
      additionalProperties: false
    AMCS.IoT.Contamination.Api.Integrator.OverfilledContainerEvent.ApiOverfilledContainerEventExternal:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/AMCS.IoT.Contamination.Api.Integrator.OverfilledContainerEvent.ApiOverfilledContainerEventExternalResourceItem'
      additionalProperties: false
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type:
          - string
          - 'null'
        cursor:
          type:
          - string
          - 'null'
        since:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceChanges_ApiOverfilledContainerEventExternalResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.IoT.Contamination.Api.Integrator.OverfilledContainerEvent.ApiOverfilledContainerEventExternal'
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type:
          - string
          - 'null'
      additionalProperties: false
