openapi: 3.2.0
info:
  title: Core User Preference API
  version: core
tags:
- name: UserPreference
paths:
  /services/api/userPreference:
    get:
      tags:
      - UserPreference
      parameters:
      - name: key
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
      summary: Get services api user preference
      x-summary-source: derived
      operationId: getServicesApiUserPreference
      x-operation-id-source: derived
    post:
      tags:
      - UserPreference
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.Core.Entity.Api.User.UserPreference'
          text/json:
            schema:
              $ref: '#/components/schemas/AMCS.Core.Entity.Api.User.UserPreference'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AMCS.Core.Entity.Api.User.UserPreference'
      responses:
        '200':
          description: Success
      summary: Create services api user preference
      x-summary-source: derived
      operationId: postServicesApiUserPreference
      x-operation-id-source: derived
components:
  schemas:
    AMCS.Core.Entity.Api.User.UserPreference:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tempIdentifier:
          type:
          - string
          - 'null'
        userPreferenceId:
          type:
          - integer
          - 'null'
          format: int32
        userIdentity:
          type:
          - string
          - 'null'
        tenantId:
          type:
          - string
          - 'null'
          format: uuid
        key:
          type:
          - string
          - 'null'
        value:
          type:
          - string
          - 'null'
      additionalProperties: false
