openapi: 3.2.0
info:
  title: Core API Workflow Get Instance State Service API
  version: core
tags:
- name: ApiWorkflowGetInstanceStateService
paths:
  /services/api/workflow/instances/{id}/op/get:
    post:
      tags:
      - ApiWorkflowGetInstanceStateService
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.ApiService.Workflow.ApiWorkflowGetInstanceStateResponse'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCS.ApiService.Workflow.ApiWorkflowGetInstanceStateResponse'
      summary: Create services api workflow instances by id op get
      x-summary-source: derived
      operationId: postServicesApiWorkflowInstancesByIdOpGet
      x-operation-id-source: derived
components:
  schemas:
    AMCS.ApiService.Workflow.ApiWorkflowGetInstanceStateResponse:
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        value:
          type:
          - string
          - 'null'
        dataType:
          type:
          - string
          - 'null'
      additionalProperties: false
