openapi: 3.0.1
info:
  title: Core AccessGroup ApplicationUISettings API
  version: core
tags:
- name: ApplicationUISettings
paths:
  /applicationUISettings:
    get:
      tags:
      - ApplicationUISettings
      responses:
        '200':
          description: Success
