openapi: 3.2.0
info:
  title: Core Work Center Icon API
  version: core
tags:
- name: WorkCenterIcon
paths:
  /services/api/workcentericons:
    get:
      tags:
      - WorkCenterIcon
      responses:
        '200':
          description: Success
      summary: Get services api workcentericons
      x-summary-source: derived
      operationId: getServicesApiWorkcentericons
      x-operation-id-source: derived
