openapi: 3.2.0
info:
  title: Core Plugin Web Hook API
  version: core
tags:
- name: PluginWebHook
paths:
  /plugin/web-hooks:
    post:
      tags:
      - PluginWebHook
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.WebHook.PluginWebHook'
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.WebHook.PluginWebHook'
          text/json:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.WebHook.PluginWebHook'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.WebHook.PluginWebHook'
      responses:
        '200':
          description: Success
      summary: Create plugin web hooks
      x-summary-source: derived
      operationId: postPluginWebHooks
      x-operation-id-source: derived
    delete:
      tags:
      - PluginWebHook
      parameters:
      - name: webHookGuid
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
      summary: Delete plugin web hooks
      x-summary-source: derived
      operationId: deletePluginWebHooks
      x-operation-id-source: derived
  /plugins/web-hook:
    post:
      tags:
      - PluginWebHook
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.WebHook.PluginWebHook'
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.WebHook.PluginWebHook'
          text/json:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.WebHook.PluginWebHook'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AMCS.PluginData.Data.WebHook.PluginWebHook'
      responses:
        '200':
          description: Success
      summary: Create plugins web hook
      x-summary-source: derived
      operationId: postPluginsWebHook
      x-operation-id-source: derived
    delete:
      tags:
      - PluginWebHook
      parameters:
      - name: targetPlugin
        in: query
        schema:
          type: string
      - name: webHookGuid
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
      summary: Delete plugins web hook
      x-summary-source: derived
      operationId: deletePluginsWebHook
      x-operation-id-source: derived
  /plugins/web-hook/ui:
    get:
      tags:
      - PluginWebHook
      responses:
        '200':
          description: Success
      summary: Get plugins web hook ui
      x-summary-source: derived
      operationId: getPluginsWebHookUi
      x-operation-id-source: derived
components:
  schemas:
    AMCS.PluginData.Data.WebHook.PluginWebHook:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        trigger:
          enum:
          - None
          - Save
          - Insert
          - Update
          - Delete
          - PreSave
          - PreInsert
          - PreUpdate
          - PreDelete
          type: string
        triggerFromString:
          type:
          - string
          - 'null'
        format:
          enum:
          - Simple
          - Full
          - Coalesce
          type: string
        httpMethod:
          type:
          - string
          - 'null'
        basicCredentials:
          $ref: '#/components/schemas/AMCS.PluginData.Data.WebHook.BasicCredentials'
        url:
          type:
          - string
          - 'null'
        filter:
          type:
          - string
          - 'null'
        headers:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    AMCS.PluginData.Data.WebHook.BasicCredentials:
      type: object
      properties:
        username:
          type:
          - string
          - 'null'
        password:
          type:
          - string
          - 'null'
      additionalProperties: false
