openapi: 3.2.0
info:
  title: Core Plugin Configuration API
  version: core
tags:
- name: Plugin Configuration
paths:
  /.well-known/amcs-plugin-configuration:
    get:
      tags:
      - Plugin Configuration
      responses:
        '200':
          description: Success
      summary: Get well known amcs plugin configuration
      x-summary-source: derived
      operationId: getWellKnownAmcsPluginConfiguration
      x-operation-id-source: derived
