openapi: 3.2.0
info:
  title: Core Job Post API
  version: core
tags:
- name: JobPost
paths:
  /jobsystem/jobPosts/changes:
    get:
      tags:
      - JobPost
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges_ApiJobPostResource'
      summary: Get jobsystem job posts changes
      x-summary-source: derived
      operationId: getJobsystemJobPostsChanges
      x-operation-id-source: derived
  /jobsystem/jobPosts/template:
    get:
      tags:
      - JobPost
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResult_ApiJobPostResource'
      summary: Get jobsystem job posts template
      x-summary-source: derived
      operationId: getJobsystemJobPostsTemplate
      x-operation-id-source: derived
  /jobsystem/jobPosts/{id}:
    get:
      tags:
      - JobPost
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: include
        in: query
        schema:
          type: string
      - name: expand
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity_ApiJobPostResource'
      summary: Get jobsystem job posts by id
      x-summary-source: derived
      operationId: getJobsystemJobPostsById
      x-operation-id-source: derived
    put:
      tags:
      - JobPost
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Replace jobsystem job posts by id
      x-summary-source: derived
      operationId: putJobsystemJobPostsById
      x-operation-id-source: derived
    delete:
      tags:
      - JobPost
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResource'
      summary: Delete jobsystem job posts by id
      x-summary-source: derived
      operationId: deleteJobsystemJobPostsById
      x-operation-id-source: derived
  /jobsystem/jobPosts/{id}/blob/{blobMemberName}:
    get:
      tags:
      - JobPost
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: blobMemberName
        in: path
        required: true
        schema:
          type: string
      - name: fileName
        in: query
        schema:
          type: string
      - name: contentType
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
      summary: Get jobsystem job posts by id blob by blob member name
      x-summary-source: derived
      operationId: getJobsystemJobPostsByIdBlobByBlobMemberName
      x-operation-id-source: derived
  /jobsystem/jobPosts:
    get:
      tags:
      - JobPost
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: order
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: includeCount
        in: query
        schema:
          type: string
      - name: includeDeleted
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection_ApiJobPostResource'
      summary: Get jobsystem job posts
      x-summary-source: derived
      operationId: getJobsystemJobPosts
      x-operation-id-source: derived
    post:
      tags:
      - JobPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Create jobsystem job posts
      x-summary-source: derived
      operationId: postJobsystemJobPosts
      x-operation-id-source: derived
components:
  schemas:
    ApiResourceChanges_ApiJobPostResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.JobSystem.ApiJobPost'
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
    AMCS.Core.Entity.Api.JobSystem.ApiJobPost:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tempIdentifier:
          type:
          - string
          - 'null'
        friendlyName:
          type:
          - string
          - 'null'
        handler:
          type:
          - string
          - 'null'
        queue:
          type:
          - string
          - 'null'
        parameters:
          type:
          - string
          - 'null'
        deadline:
          type:
          - integer
          - 'null'
          format: int32
        persistenceMode:
          type: integer
          format: int32
        duplicateMode:
          type: integer
          format: int32
      additionalProperties: false
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type:
          - string
          - 'null'
        cursor:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiResourceResultEntity_ApiJobPostResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.JobSystem.ApiJobPost'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
      additionalProperties: false
    ApiResourceId:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: integer
          format: int32
      additionalProperties: false
    ApiResourceResult_ApiJobPostResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.JobSystem.ApiJobPost'
      additionalProperties: false
    ApiResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
      additionalProperties: false
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - object
            - 'null'
            additionalProperties: {}
        include:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - array
            - 'null'
            items:
              type: object
              additionalProperties: {}
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceResultCollection_ApiJobPostResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.JobSystem.ApiJobPost'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
      additionalProperties: false
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type:
          - string
          - 'null'
        associations:
          type:
          - array
          - 'null'
          items:
            type: string
        expand:
          type:
          - array
          - 'null'
          items:
            type: string
        operations:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
