openapi: 3.0.1
info:
  title: Core AccessGroup Diagnostics API
  version: core
tags:
- name: Diagnostics
paths:
  /diagnostics:
    get:
      tags:
      - Diagnostics
      parameters:
      - name: run
        in: query
        schema:
          type: string
      - name: format
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
