openapi: 3.2.0
info:
  title: Core Udf Workflow Activity API
  version: core
tags:
- name: UdfWorkflowActivity
paths:
  /plugin/activities/readUdf:
    post:
      tags:
      - UdfWorkflowActivity
      parameters:
      - name: type
        in: query
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.ApiService.Controllers.Plugin.RequestObjects.ReadUdfRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/AMCS.ApiService.Controllers.Plugin.RequestObjects.ReadUdfRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AMCS.ApiService.Controllers.Plugin.RequestObjects.ReadUdfRequest'
      responses:
        '200':
          description: Success
      summary: Create plugin activities read udf
      x-summary-source: derived
      operationId: postPluginActivitiesReadUdf
      x-operation-id-source: derived
  /plugin/activities/writeUdf:
    post:
      tags:
      - UdfWorkflowActivity
      parameters:
      - name: type
        in: query
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.ApiService.Controllers.Plugin.RequestObjects.WriteUdfRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/AMCS.ApiService.Controllers.Plugin.RequestObjects.WriteUdfRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AMCS.ApiService.Controllers.Plugin.RequestObjects.WriteUdfRequest'
      responses:
        '200':
          description: Success
      summary: Create plugin activities write udf
      x-summary-source: derived
      operationId: postPluginActivitiesWriteUdf
      x-operation-id-source: derived
components:
  schemas:
    AMCS.ApiService.Controllers.Plugin.RequestObjects.WriteUdfRequest:
      type: object
      properties:
        objectName:
          type:
          - string
          - 'null'
        id:
          type: string
          format: uuid
        fieldName:
          type:
          - string
          - 'null'
        value: {}
      additionalProperties: false
    AMCS.ApiService.Controllers.Plugin.RequestObjects.ReadUdfRequest:
      type: object
      properties:
        objectName:
          type:
          - string
          - 'null'
        id:
          type: string
          format: uuid
        fieldName:
          type:
          - string
          - 'null'
      additionalProperties: false
