openapi: 3.2.0
info:
  description: '# Getting Started


    ## Document Purpose and Scope


    The Scale REST API endpoints are technically described in this document.'
  title: Scale REST Subscriber API
  version: '9.1'
servers:
- url: http://{env}-svc-core.amcsplatform.com/scale/api/
tags:
- name: Subscriber
paths:
  /integrator/subscribers/{id}:
    get:
      tags:
      - Subscriber
      summary: Find with GUID
      description: '| Property | Description |

        | ----------------------------------------------------- | -------------------------------------------------------------- |

        | Name | The name of the Subscriber |

        | CompanyOutlets[] | The company outlets associated with the subscriber |

        | CompanyOutlets[].SubscriberOutletListItem | The SubscriberOutletListItem of the outlets for the subscriber |

        | CompanyOutlets[].SubscriberOutletListItem.Description | The company outlet description |

        | CompanyOutlets[].SubscriberOutletListItem.AbbreviatedDescription | The company outlet abbreviated description |

        | CompanyOutlets[].SubscriberOutletListItem.Guid | The company Outlet Guid |

        | RelatedSubscriberOutletGuid | The Related Subscriber Outlet Guid |

        | GUID | The Subscriber Guid |'
      operationId: Subscriber_Get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: links
        in: query
        required: false
        schema:
          type: string
      - name: include
        in: query
        required: false
        schema:
          type: string
      - name: expand
        in: query
        required: false
        schema:
          type: string
      - name: udf
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity_ApiSubscriberResource'
    put:
      tags:
      - Subscriber
      summary: Partial update
      description: '| Property | Description | Required |

        |-------------------------------------------------------|------------------------------------------------------------------------|----------|

        | Name | The name of the Subscriber | No |

        | CompanyOutlets[] | The company outlets associated with the subscriber | Yes |

        | CompanyOutlets[].SubscriberOutletListItem | The SubscriberOutletListItem of the outlets for the subscriber | Yes |

        | CompanyOutlets[].SubscriberOutletListItem.Description | The company outlet description | No |

        | CompanyOutlets[].SubscriberOutletListItem.Guid | The company Outlet Guid | Yes |

        | RelatedSubscriberOutletGuid | The Related Subscriber Outlet Guid, required if it needs to be updated | No |

        | GUID | The Subscriber Guid | No |'
      operationId: Subscriber_Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
        required: true
  /integrator/subscribers:
    get:
      tags:
      - Subscriber
      summary: Find with Filters
      description: '| Property | Description |

        | ----------------------------------------------------- | -------------------------------------------------------------- |

        | Name | The name of the Subscriber |

        | CompanyOutlets[] | The company outlets associated with the subscriber |

        | CompanyOutlets[].SubscriberOutletListItem | The SubscriberOutletListItem of the outlets for the subscriber |

        | CompanyOutlets[].SubscriberOutletListItem.Description | The company outlet description |

        | CompanyOutlets[].SubscriberOutletListItem.AbbreviatedDescription | The company outlet abbreviated description |

        | CompanyOutlets[].SubscriberOutletListItem.Guid | The company Outlet Guid |

        | RelatedSubscriberOutletGuid | The Related Subscriber Outlet Guid |

        | GUID | The Subscriber Guid |'
      operationId: Subscriber_GetCollection
      parameters:
      - name: filter
        in: query
        required: false
        schema:
          type: string
      - name: search
        in: query
        required: false
        schema:
          type: string
      - name: order
        in: query
        required: false
        schema:
          type: string
      - name: max
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: includeCount
        in: query
        required: false
        schema:
          type: boolean
      - name: includeDeleted
        in: query
        required: false
        schema:
          type: boolean
      - name: links
        in: query
        required: false
        schema:
          type: string
      - name: udf
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection_ApiSubscriberResource'
    post:
      tags:
      - Subscriber
      summary: Create or update
      description: '# Subscribers


        | Property | Description | Required |

        |-------------------------------------------------------|----------------------------------------------------------------|----------|

        | Name | The name of the Subscriber | Yes |

        | CompanyOutlets[] | The company outlets associated with the subscriber | Yes |

        | CompanyOutlets[].SubscriberOutletListItem | The SubscriberOutletListItem of the outlets for the subscriber | Yes |

        | CompanyOutlets[].SubscriberOutletListItem.Description | The company outlet description | No |

        | CompanyOutlets[].SubscriberOutletListItem.Guid | The company Outlet Guid | Yes |

        | RelatedSubscriberOutletGuid | The Related Subscriber Outlet Guid | No |

        | GUID | The Subscriber Guid | No |'
      operationId: Subscriber_Create
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
        required: true
components:
  schemas:
    ApiIntegratorListItemResource:
      type: object
      properties:
        Description:
          type: string
        AbbreviatedDescription:
          type: string
        Guid:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceStatus:
      type: object
      properties:
        id:
          format: int32
          type: integer
        isSuccess:
          type: boolean
    ApiResourceResultEntity_ApiSubscriberResource:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/ApiSubscriberResource'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultCollection_ApiSubscriberResource:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiSubscriberResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceId:
      type: object
      properties:
        resource:
          format: int32
          type: integer
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties:
                type: object
    ApiSubscriberCompanyOutletResource:
      type: object
      properties:
        SubscriberOutletListItem:
          $ref: '#/components/schemas/ApiIntegratorListItemResource'
        RelatedSubscriberOutletGuid:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiSubscriberResource:
      type: object
      properties:
        Name:
          type: string
        CompanyOutlets:
          type: array
          items:
            $ref: '#/components/schemas/ApiSubscriberCompanyOutletResource'
        GUID:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          format: int32
          type: integer
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
        associations:
          type: array
          items:
            type: string
        expand:
          type: array
          items:
            type: string
        operations:
          type: array
          items:
            type: string
