openapi: 3.0.1
info:
  title: Core AccessGroup TenantRegistration API
  version: core
tags:
- name: TenantRegistration
paths:
  /plugins/register-tenant:
    post:
      tags:
      - TenantRegistration
      responses:
        '200':
          description: Success
  /plugins/un-register-tenant:
    post:
      tags:
      - TenantRegistration
      responses:
        '200':
          description: Success
