openapi: 3.2.0
info:
  title: Core Tenant Registration API
  version: core
tags:
- name: TenantRegistration
paths:
  /plugins/register-tenant:
    post:
      tags:
      - TenantRegistration
      responses:
        '200':
          description: Success
      summary: Create plugins register tenant
      x-summary-source: derived
      operationId: postPluginsRegisterTenant
      x-operation-id-source: derived
  /plugins/un-register-tenant:
    post:
      tags:
      - TenantRegistration
      responses:
        '200':
          description: Success
      summary: Create plugins un register tenant
      x-summary-source: derived
      operationId: postPluginsUnRegisterTenant
      x-operation-id-source: derived
