openapi: 3.0.1
info:
  title: Core AccessGroup SiteType API
  version: core
tags:
- name: SiteType
paths:
  /lists/siteTypes/{guid}:
    get:
      tags:
      - SiteType
      summary: Find with GUID
      description: "| Property                  | Description                                                       |\r\n| ------------------------- | ----------------------------------------------------------------- |\r\n| GUID                      | The GUID associated to the site type                              |\r\n| Description               | The description of the site type                                  |\r\n| IsDeleted                 | Whether the site type is deleted  |"
      operationId: SiteType_Get
      parameters:
      - name: guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ApiIntegratorSiteTypeResource]'
  /lists/siteTypes:
    get:
      tags:
      - SiteType
      summary: Find with Filters
      description: "| Property                  | Description                                                       |\r\n| ------------------------- | ----------------------------------------------------------------- |\r\n| GUID                      | The GUID associated to the site type                              |\r\n| Description               | The description of the site type                                  |\r\n| IsDeleted                 | Whether the site type is deleted  |"
      operationId: SiteType_GetCollection
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: includeCount
        in: query
        schema:
          type: boolean
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiIntegratorSiteTypeResource]'
components:
  schemas:
    ApiResourceResultEntity[ApiIntegratorSiteTypeResource]:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/ApiIntegratorSiteTypeResource'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiIntegratorSiteTypeResource:
      type: object
      properties:
        Description:
          type: string
        IsDeleted:
          type: boolean
        GUID:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties:
                type: object
    ApiResourceResultCollection[ApiIntegratorSiteTypeResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorSiteTypeResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
        associations:
          type: array
          items:
            type: string
        expand:
          type: array
          items:
            type: string
        operations:
          type: array
          items:
            type: string
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
        isSuccess:
          type: boolean
