openapi: 3.2.0
info:
  title: Core API Workflow Instance Delete Service API
  version: core
tags:
- name: ApiWorkflowInstanceDeleteService
paths:
  /services/api/workflow/instances/{id}/op/delete:
    post:
      tags:
      - ApiWorkflowInstanceDeleteService
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCS.ApiService.Workflow.ApiWorkflowInstanceDeleteResponse'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCS.ApiService.Workflow.ApiWorkflowInstanceDeleteResponse'
      summary: Create services api workflow instances by id op delete
      x-summary-source: derived
      operationId: postServicesApiWorkflowInstancesByIdOpDelete
      x-operation-id-source: derived
components:
  schemas:
    AMCS.ApiService.Workflow.ApiWorkflowInstanceDeleteResponse:
      type: object
      additionalProperties: false
