openapi: 3.2.0
info:
  title: Core Definition Browser API
  version: core
tags:
- name: DefinitionBrowser
paths:
  /services/api/workflow/definitionBrowsers/changes:
    get:
      tags:
      - DefinitionBrowser
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges_ApiWorkflowDefinitionBrowserResource'
      summary: Get services api workflow definition browsers changes
      x-summary-source: derived
      operationId: getServicesApiWorkflowDefinitionBrowsersChanges
      x-operation-id-source: derived
  /services/api/workflow/definitionBrowsers/template:
    get:
      tags:
      - DefinitionBrowser
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResult_ApiWorkflowDefinitionBrowserResource'
      summary: Get services api workflow definition browsers template
      x-summary-source: derived
      operationId: getServicesApiWorkflowDefinitionBrowsersTemplate
      x-operation-id-source: derived
  /services/api/workflow/definitionBrowsers/{id}:
    get:
      tags:
      - DefinitionBrowser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: include
        in: query
        schema:
          type: string
      - name: expand
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity_ApiWorkflowDefinitionBrowserResource'
      summary: Get services api workflow definition browsers by id
      x-summary-source: derived
      operationId: getServicesApiWorkflowDefinitionBrowsersById
      x-operation-id-source: derived
    put:
      tags:
      - DefinitionBrowser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Replace services api workflow definition browsers by id
      x-summary-source: derived
      operationId: putServicesApiWorkflowDefinitionBrowsersById
      x-operation-id-source: derived
    delete:
      tags:
      - DefinitionBrowser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResource'
      summary: Delete services api workflow definition browsers by id
      x-summary-source: derived
      operationId: deleteServicesApiWorkflowDefinitionBrowsersById
      x-operation-id-source: derived
  /services/api/workflow/definitionBrowsers/{id}/blob/{blobMemberName}:
    get:
      tags:
      - DefinitionBrowser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: blobMemberName
        in: path
        required: true
        schema:
          type: string
      - name: fileName
        in: query
        schema:
          type: string
      - name: contentType
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
      summary: Get services api workflow definition browsers by id blob by blob member name
      x-summary-source: derived
      operationId: getServicesApiWorkflowDefinitionBrowsersByIdBlobByBlobMemberName
      x-operation-id-source: derived
  /services/api/workflow/definitionBrowsers:
    get:
      tags:
      - DefinitionBrowser
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: order
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: includeCount
        in: query
        schema:
          type: string
      - name: includeDeleted
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection_ApiWorkflowDefinitionBrowserResource'
      summary: Get services api workflow definition browsers
      x-summary-source: derived
      operationId: getServicesApiWorkflowDefinitionBrowsers
      x-operation-id-source: derived
    post:
      tags:
      - DefinitionBrowser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Create services api workflow definition browsers
      x-summary-source: derived
      operationId: postServicesApiWorkflowDefinitionBrowsers
      x-operation-id-source: derived
components:
  schemas:
    ApiResourceResult_ApiWorkflowDefinitionBrowserResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowDefinitionBrowser'
      additionalProperties: false
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type:
          - string
          - 'null'
        cursor:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiResourceResultCollection_ApiWorkflowDefinitionBrowserResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowDefinitionBrowser'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
      additionalProperties: false
    AMCS.Core.Entity.Api.Workflow.ApiWorkflowDefinitionBrowser:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tempIdentifier:
          type:
          - string
          - 'null'
        workflowDefinitionId:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        providerId:
          type:
          - integer
          - 'null'
          format: int32
        providerName:
          type:
          - string
          - 'null'
        providerDescription:
          type:
          - string
          - 'null'
        scheduleJobId:
          type:
          - integer
          - 'null'
          format: int32
        designerUrl:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceId:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: integer
          format: int32
      additionalProperties: false
    ApiResourceResultEntity_ApiWorkflowDefinitionBrowserResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowDefinitionBrowser'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
      additionalProperties: false
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type:
          - string
          - 'null'
        associations:
          type:
          - array
          - 'null'
          items:
            type: string
        expand:
          type:
          - array
          - 'null'
          items:
            type: string
        operations:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    ApiResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
      additionalProperties: false
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - object
            - 'null'
            additionalProperties: {}
        include:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - array
            - 'null'
            items:
              type: object
              additionalProperties: {}
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
    ApiResourceChanges_ApiWorkflowDefinitionBrowserResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowDefinitionBrowser'
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
