openapi: 3.0.1
info:
  title: Core AccessGroup DayOfWeek API
  version: core
tags:
- name: DayOfWeek
paths:
  /lists/dayOfWeeks/{guid}:
    get:
      tags:
      - DayOfWeek
      summary: Find with GUID
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the day of week        |\r\n| DayOfWeek                | The name of the day of week    |\r\n| Descriminator| The numerical value of the day of week   |\r\n| DatePartValue| The datepart value of the day of week   |"
      operationId: DayOfWeek_Get
      parameters:
      - name: guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ApiIntegratorDayOfWeekResource]'
  /lists/dayOfWeeks:
    get:
      tags:
      - DayOfWeek
      summary: Find with Filters
      description: "| Property                  | Description                                                              |\r\n| ------------------------- | ------------------------------------------------------------------------ |\r\n| GUID                      | The GUID associated to the day of week        |\r\n| DayOfWeek                | The name of the day of week    |\r\n| Descriminator| The numerical value of the day of week   |\r\n| DatePartValue| The datepart value of the day of week   |"
      operationId: DayOfWeek_GetCollection
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: includeCount
        in: query
        schema:
          type: boolean
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiIntegratorDayOfWeekResource]'
components:
  schemas:
    ApiResourceResultEntity[ApiIntegratorDayOfWeekResource]:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/ApiIntegratorDayOfWeekResource'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiIntegratorDayOfWeekResource:
      type: object
      properties:
        DayOfWeek:
          type: string
        Descriminator:
          type: integer
          format: int32
        DatePartValue:
          type: integer
          format: int32
        GUID:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties:
                type: object
    ApiResourceResultCollection[ApiIntegratorDayOfWeekResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorDayOfWeekResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
        associations:
          type: array
          items:
            type: string
        expand:
          type: array
          items:
            type: string
        operations:
          type: array
          items:
            type: string
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
        isSuccess:
          type: boolean
