openapi: 3.2.0
info:
  title: Core Definition Schedule API
  version: core
tags:
- name: DefinitionSchedule
paths:
  /services/api/workflow/definitionSchedules/changes:
    get:
      tags:
      - DefinitionSchedule
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges_ApiWorkflowDefinitionScheduleResource'
      summary: Get services api workflow definition schedules changes
      x-summary-source: derived
      operationId: getServicesApiWorkflowDefinitionSchedulesChanges
      x-operation-id-source: derived
  /services/api/workflow/definitionSchedules/template:
    get:
      tags:
      - DefinitionSchedule
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResult_ApiWorkflowDefinitionScheduleResource'
      summary: Get services api workflow definition schedules template
      x-summary-source: derived
      operationId: getServicesApiWorkflowDefinitionSchedulesTemplate
      x-operation-id-source: derived
  /services/api/workflow/definitionSchedules/{id}:
    get:
      tags:
      - DefinitionSchedule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: include
        in: query
        schema:
          type: string
      - name: expand
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity_ApiWorkflowDefinitionScheduleResource'
      summary: Get services api workflow definition schedules by id
      x-summary-source: derived
      operationId: getServicesApiWorkflowDefinitionSchedulesById
      x-operation-id-source: derived
    put:
      tags:
      - DefinitionSchedule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Replace services api workflow definition schedules by id
      x-summary-source: derived
      operationId: putServicesApiWorkflowDefinitionSchedulesById
      x-operation-id-source: derived
    delete:
      tags:
      - DefinitionSchedule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResource'
      summary: Delete services api workflow definition schedules by id
      x-summary-source: derived
      operationId: deleteServicesApiWorkflowDefinitionSchedulesById
      x-operation-id-source: derived
  /services/api/workflow/definitionSchedules/{id}/blob/{blobMemberName}:
    get:
      tags:
      - DefinitionSchedule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: blobMemberName
        in: path
        required: true
        schema:
          type: string
      - name: fileName
        in: query
        schema:
          type: string
      - name: contentType
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
      summary: Get services api workflow definition schedules by id blob by blob member name
      x-summary-source: derived
      operationId: getServicesApiWorkflowDefinitionSchedulesByIdBlobByBlobMemberName
      x-operation-id-source: derived
  /services/api/workflow/definitionSchedules:
    get:
      tags:
      - DefinitionSchedule
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: order
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: includeCount
        in: query
        schema:
          type: string
      - name: includeDeleted
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection_ApiWorkflowDefinitionScheduleResource'
      summary: Get services api workflow definition schedules
      x-summary-source: derived
      operationId: getServicesApiWorkflowDefinitionSchedules
      x-operation-id-source: derived
    post:
      tags:
      - DefinitionSchedule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
      summary: Create services api workflow definition schedules
      x-summary-source: derived
      operationId: postServicesApiWorkflowDefinitionSchedules
      x-operation-id-source: derived
components:
  schemas:
    ApiResourceResultEntity_ApiWorkflowDefinitionScheduleResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowDefinitionSchedule'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
      additionalProperties: false
    ApiResourceChanges_ApiWorkflowDefinitionScheduleResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowDefinitionSchedule'
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type:
          - string
          - 'null'
        cursor:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceResult_ApiWorkflowDefinitionScheduleResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowDefinitionSchedule'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiResourceId:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: integer
          format: int32
      additionalProperties: false
    AMCS.Core.Entity.Api.Workflow.ApiWorkflowDefinitionSchedule:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type:
          - integer
          - 'null'
          format: int32
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type:
          - string
          - 'null'
          format: uuid
        lastChangeReasonId:
          type:
          - integer
          - 'null'
          format: int32
        tempIdentifier:
          type:
          - string
          - 'null'
        scheduledJobId:
          type:
          - integer
          - 'null'
          format: int32
        scheduleWorkflowDefinitionId:
          type:
          - integer
          - 'null'
          format: int32
        workflowDefinitionId:
          type: string
          format: uuid
        workflowProvider:
          type:
          - string
          - 'null'
        friendlyName:
          type:
          - string
          - 'null'
        workflowStartParameters:
          type:
          - string
          - 'null'
        trigger:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceResultCollection_ApiWorkflowDefinitionScheduleResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.Workflow.ApiWorkflowDefinitionSchedule'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
      additionalProperties: false
    ApiResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
      additionalProperties: false
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - object
            - 'null'
            additionalProperties: {}
        include:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - array
            - 'null'
            items:
              type: object
              additionalProperties: {}
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type:
          - string
          - 'null'
        associations:
          type:
          - array
          - 'null'
          items:
            type: string
        expand:
          type:
          - array
          - 'null'
          items:
            type: string
        operations:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
