openapi: 3.0.1
info:
  title: Core AccessGroup ApiDocumentation API
  version: core
tags:
- name: ApiDocumentation
paths:
  /api/documentation/error/{errorCode}:
    get:
      tags:
      - ApiDocumentation
      parameters:
      - name: errorCode
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
