openapi: 3.0.1
info:
  title: Core AccessGroup SiteOrderItemState API
  version: core
tags:
- name: SiteOrderItemState
paths:
  /lists/siteOrderItemStates/{guid}:
    get:
      tags:
      - SiteOrderItemState
      summary: Find with GUID
      description: "| Property                  | Description                                                       |\r\n| ------------------------- | ----------------------------------------------------------------- |\r\n| GUID                      | The GUID associated to the site order item state                  |\r\n| Description               | The description of the site order item state                      |\r\n| IsActive| Whether the site order item state is active  |\r\n| IsDeleted                 | Whether the site order item state is deleted  |"
      operationId: SiteOrderItemState_Get
      parameters:
      - name: guid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ApiIntegratorSiteOrderItemStateResource]'
  /lists/siteOrderItemStates:
    get:
      tags:
      - SiteOrderItemState
      summary: Find with Filters
      description: "| Property                  | Description                                                       |\r\n| ------------------------- | ----------------------------------------------------------------- |\r\n| GUID                      | The GUID associated to the site order item state                  |\r\n| Description               | The description of the site order item state                      |\r\n| IsActive| Whether the site order item state is active  |\r\n| IsDeleted                 | Whether the site order item state is deleted  |"
      operationId: SiteOrderItemState_GetCollection
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: includeCount
        in: query
        schema:
          type: boolean
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiIntegratorSiteOrderItemStateResource]'
components:
  schemas:
    ApiResourceResultEntity[ApiIntegratorSiteOrderItemStateResource]:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/ApiIntegratorSiteOrderItemStateResource'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceResultCollection[ApiIntegratorSiteOrderItemStateResource]:
      type: object
      properties:
        resource:
          type: array
          items:
            $ref: '#/components/schemas/ApiIntegratorSiteOrderItemStateResource'
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
    ApiIntegratorSiteOrderItemStateResource:
      type: object
      properties:
        Description:
          type: string
        IsActive:
          type: boolean
        IsDeleted:
          type: boolean
        GUID:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties:
                type: object
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
        associations:
          type: array
          items:
            type: string
        expand:
          type: array
          items:
            type: string
        operations:
          type: array
          items:
            type: string
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
        isSuccess:
          type: boolean
