openapi: 3.0.1
info:
  title: Core AccessGroup CommsServerSyncStatus API
  version: core
tags:
- name: CommsServerSyncStatus
paths:
  /commsServerSyncStatus:
    get:
      tags:
      - CommsServerSyncStatus
      responses:
        '200':
          description: Success
