openapi: 3.0.1
info:
  title: Core AccessGroup ReverseProxyRule API
  version: core
tags:
- name: ReverseProxyRule
paths:
  /services/api/reverseProxyRules/changes:
    get:
      tags:
      - ReverseProxyRule
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges[ReverseProxyRuleResource]'
  /services/api/reverseProxyRules/template:
    get:
      tags:
      - ReverseProxyRule
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResult[ReverseProxyRuleResource]'
  /services/api/reverseProxyRules/{id}:
    get:
      tags:
      - ReverseProxyRule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: include
        in: query
        schema:
          type: string
      - name: expand
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ReverseProxyRuleResource]'
    put:
      tags:
      - ReverseProxyRule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
    delete:
      tags:
      - ReverseProxyRule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResource'
  /services/api/reverseProxyRules/{id}/blob/{blobMemberName}:
    get:
      tags:
      - ReverseProxyRule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: blobMemberName
        in: path
        required: true
        schema:
          type: string
      - name: fileName
        in: query
        schema:
          type: string
      - name: contentType
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
  /services/api/reverseProxyRules:
    get:
      tags:
      - ReverseProxyRule
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: order
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: includeCount
        in: query
        schema:
          type: string
      - name: includeDeleted
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ReverseProxyRuleResource]'
    post:
      tags:
      - ReverseProxyRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
components:
  schemas:
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type: string
          nullable: true
        cursor:
          type: string
          nullable: true
      additionalProperties: false
    ApiResourceId:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: integer
          format: int32
      additionalProperties: false
    AMCS.Core.Entity.ReverseProxyRuleEntity:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type: integer
          format: int32
          nullable: true
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type: string
          format: uuid
          nullable: true
        lastChangeReasonId:
          type: integer
          format: int32
          nullable: true
        tempIdentifier:
          type: string
          nullable: true
        reverseProxyRuleId:
          type: integer
          format: int32
          nullable: true
        name:
          type: string
          nullable: true
        systemCategory:
          type: string
          nullable: true
        prefix:
          type: string
          nullable: true
        target:
          type: string
          nullable: true
        containerNavigationPrefix:
          type: string
          nullable: true
        isIgnoreProxy:
          type: boolean
      additionalProperties: false
    ApiResourceResultEntity[ReverseProxyRuleResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.ReverseProxyRuleEntity'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
          nullable: true
      additionalProperties: false
    ApiResourceResult[ReverseProxyRuleResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.ReverseProxyRuleEntity'
      additionalProperties: false
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    ApiResourceChanges[ReverseProxyRuleResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: array
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.ReverseProxyRuleEntity'
          nullable: true
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
    ApiResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
      additionalProperties: false
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties: {}
            nullable: true
          nullable: true
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties: {}
            nullable: true
          nullable: true
      additionalProperties: false
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
          nullable: true
        associations:
          type: array
          items:
            type: string
          nullable: true
        expand:
          type: array
          items:
            type: string
          nullable: true
        operations:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
    ApiResourceResultCollection[ReverseProxyRuleResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: array
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.ReverseProxyRuleEntity'
          nullable: true
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
          nullable: true
        isSuccess:
          type: boolean
      additionalProperties: false
