openapi: 3.2.0
info:
  title: Core Moment Time Zone Database API
  version: core
tags:
- name: MomentTimeZoneDatabase
paths:
  /momentTimeZoneDatabase:
    get:
      tags:
      - MomentTimeZoneDatabase
      responses:
        '200':
          description: Success
      summary: Get moment time zone database
      x-summary-source: derived
      operationId: getMomentTimeZoneDatabase
      x-operation-id-source: derived
