openapi: 3.0.1
info:
  title: Core AccessGroup JobHandler API
  version: core
tags:
- name: JobHandler
paths:
  /jobsystem/jobHandlers/changes:
    get:
      tags:
      - JobHandler
      parameters:
      - name: since
        in: query
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceChanges[ApiJobHandlerResource]'
  /jobsystem/jobHandlers/template:
    get:
      tags:
      - JobHandler
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResult[ApiJobHandlerResource]'
  /jobsystem/jobHandlers/{id}:
    get:
      tags:
      - JobHandler
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: include
        in: query
        schema:
          type: string
      - name: expand
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultEntity[ApiJobHandlerResource]'
    put:
      tags:
      - JobHandler
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
    delete:
      tags:
      - JobHandler
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResource'
  /jobsystem/jobHandlers/{id}/blob/{blobMemberName}:
    get:
      tags:
      - JobHandler
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: blobMemberName
        in: path
        required: true
        schema:
          type: string
      - name: fileName
        in: query
        schema:
          type: string
      - name: contentType
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
  /jobsystem/jobHandlers:
    get:
      tags:
      - JobHandler
      parameters:
      - name: filter
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      - name: order
        in: query
        schema:
          type: string
      - name: max
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: includeCount
        in: query
        schema:
          type: string
      - name: includeDeleted
        in: query
        schema:
          type: string
      - name: links
        in: query
        schema:
          type: string
      - name: udf
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceResultCollection[ApiJobHandlerResource]'
    post:
      tags:
      - JobHandler
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResourceId'
components:
  schemas:
    AMCS.Core.Entity.Api.JobSystem.ApiJobHandler:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type: integer
          format: int32
          nullable: true
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type: string
          format: uuid
          nullable: true
        lastChangeReasonId:
          type: integer
          format: int32
          nullable: true
        tempIdentifier:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
        displayName:
          type: string
          nullable: true
        allowScheduling:
          type: boolean
        duplicateMode:
          type: string
          nullable: true
        requestParameterInfo:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.JobSystem.ApiJobHandlerParameter'
        compatibleQueues:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
    ApiResourceResultUpdatesExtra:
      type: object
      properties:
        until:
          type: string
          nullable: true
        cursor:
          type: string
          nullable: true
      additionalProperties: false
    AMCS.Core.Entity.Api.JobSystem.ApiJobHandlerParameter:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type: integer
          format: int32
          nullable: true
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type: string
          format: uuid
          nullable: true
        lastChangeReasonId:
          type: integer
          format: int32
          nullable: true
        tempIdentifier:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
        properties:
          type: array
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.JobSystem.ApiJobHandlerProperty'
          nullable: true
      additionalProperties: false
    ApiResourceResult[ApiJobHandlerResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.JobSystem.ApiJobHandler'
      additionalProperties: false
    AMCS.Core.Entity.Api.JobSystem.ApiJobHandlerProperty:
      type: object
      properties:
        isValid:
          type: boolean
          readOnly: true
        id:
          type: integer
          format: int32
          nullable: true
          readOnly: true
        id32:
          type: integer
          format: int32
          readOnly: true
        guid:
          type: string
          format: uuid
          nullable: true
        lastChangeReasonId:
          type: integer
          format: int32
          nullable: true
        tempIdentifier:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        displayName:
          type: string
          nullable: true
        isRequired:
          type: boolean
        isList:
          type: boolean
        type:
          type: string
          nullable: true
      additionalProperties: false
    ApiResourceChanges[ApiJobHandlerResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: array
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.JobSystem.ApiJobHandler'
          nullable: true
        extra:
          $ref: '#/components/schemas/ApiResourceResultUpdatesExtra'
      additionalProperties: false
    ApiResourceId:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: integer
          format: int32
      additionalProperties: false
    ApiResourceErrors:
      type: object
      properties:
        errors:
          type: string
          nullable: true
      additionalProperties: false
    ApiResourceResultCollectionExtra:
      type: object
      properties:
        count:
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    ApiResourceResultEntity[ApiJobHandlerResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          $ref: '#/components/schemas/AMCS.Core.Entity.Api.JobSystem.ApiJobHandler'
        links:
          $ref: '#/components/schemas/ApiResourceResultEntityLinks'
        extra:
          $ref: '#/components/schemas/ApiResourceResultEntityExtra'
      additionalProperties: false
    ApiResource:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
      additionalProperties: false
    ApiResourceResultEntityExtra:
      type: object
      properties:
        expand:
          type: object
          additionalProperties:
            type: object
            additionalProperties: {}
            nullable: true
          nullable: true
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties: {}
            nullable: true
          nullable: true
      additionalProperties: false
    ApiResourceResultEntityLinks:
      type: object
      properties:
        self:
          type: string
          nullable: true
        associations:
          type: array
          items:
            type: string
          nullable: true
        expand:
          type: array
          items:
            type: string
          nullable: true
        operations:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
    ApiResourceStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
          nullable: true
        isSuccess:
          type: boolean
      additionalProperties: false
    ApiResourceResultCollection[ApiJobHandlerResource]:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ApiResourceErrors'
        status:
          $ref: '#/components/schemas/ApiResourceStatus'
        resource:
          type: array
          items:
            $ref: '#/components/schemas/AMCS.Core.Entity.Api.JobSystem.ApiJobHandler'
          nullable: true
        extra:
          $ref: '#/components/schemas/ApiResourceResultCollectionExtra'
      additionalProperties: false
