openapi: 3.2.0
info:
  title: AMCS Pay External Mobills IVR API
  version: external
  description: '# Getting Started


    ## Document Purpose and Scope


    The AMCS Pay REST API endpoints are technically described in this document.'
servers:
- url: https://eu1-pay-dev.amcsplatform.com/
  description: AMCSPay Developer Environment
security:
- cookieAuth: []
tags:
- name: Mobills IVR
paths:
  /Mobills/Ivr/Pay/GetCustomerInvoiceDetails:
    post:
      tags:
      - Mobills IVR
      summary: Get Customer Invoice Details
      description: 'This endpoint creates a record in payment transaction table.


        ## Request


        | Property | Description |

        | ------------------------- | ------------------------------------------------------------------------|

        | CustomerARCode | The account code used for Accounts Receivable. (AMCS will provide the account ARCode) |

        | Channel | Channel can be only MOBILL OR IVR |


        ## Response


        | Property | Description |

        | ------------------------- | ------------------------------------------------------------------------|

        | CustomerGuid | The GUID associated to the customer. |

        | CustomerName |The customer''s name. |

        | CustomerBalance |The amount associated to the payment. |

        | CustomerCurrency | Customer Currency associated with the Customer account. |

        | InvoiceDetails |It will show all the invoices associated with the account |

        | InvoiceNumber |The invoice number associated to the invoice. Filterable. |

        | InvoiceGUID |The GUID associated to the invoice. |

        | InvoiceDate |The invoiceDate associated to the invoice in ISO format (YYYY-MM-DD). |

        | ZipCode |Zip code is associated with the account |

        | InvoiceDueDate |The dueDate associated to the invoice in ISO format (YYYY-MM-DD). |

        | UnallocatedAmount |The Unallocated Amount on the customers account. |

        | InvoiceCurrency |Invoice Currency asscoaited with the customer account |

        | TransactionReference |Transaction Reference associated with account |

        | ZipCode |ZipCode associated with the account address |

        | InvoiceDate |The invoiceDate associated to the invoice in ISO format (YYYY-MM-DD). |

        | LastPaymentDate |When the last payment was made |

        | MakePaymentLink |It shows the payment link (if any invoice available) |

        | IsActive |Whether the customer is active |

        | MobillsEnrollment |Whether the mobills enrollment is active. |

        | GUID |Guid associated with the account'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCSPayMobillsIvrRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCSPayMobillsIvrResponse'
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCSPayErrorContentResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCSPayErrorResponse'
      operationId: postMobillsIvrPayGetCustomerInvoiceDetails
      x-operation-id-source: derived
  /payACIInteractiveVoiceResponse:
    post:
      tags:
      - Mobills IVR
      summary: Post Back IVR Response
      description: 'This endpoint updates an existing record in the payment transaction table and creates a record in the Amcs-Pay Database.


        ## Request


        | Property | Description |

        | ------------------------- | ------------------------------------------------------------------------|

        | TransactionReference | The Transaction Reference can get from the GetCustomerInvoce API. |

        | PaymentAmount | The payment amount associated to the payment request. |

        | Currency | Currency associated with the Customer account.|

        | Timestamp | The time stamp associated to the response payload. |

        | TransactionPaymentType | Transaction payment type can be any of "CARD", "ACH". |

        | IsIVR |IsIVR is a flag and should be set to true.. |

        | Code |The codes for successfully processed transactions. |

        | Description |Description associated with the Code. |

        | Bin |The first six digits of the card.number. |

        | Last4Digits |Last 4 digits of the "Credit", "Debit" Card. |

        | PaymentType |Payment Type DB, Debit: Debits the account of the end customer and credits the merchant account. |

        | Holder |Holder of the credit card account. |

        | ExpiryMonth | The expiry month of the card. |

        | ExpiryYear |The expiry year of the card. |

        | ConfirmationNumber |The Confirmation Number (payment reference) data sent by the provider associated to the original payment response.|


        ## Response


        | Property | Description |

        | ------------------------- | ------------------------------------------------------------------------|

        | |

        | Response |It returns the success response.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCSPayPostBackIvrRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCSPayIvrResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCSPayErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCSPayErrorResponse'
      operationId: postPayACIInteractiveVoiceResponse
      x-operation-id-source: derived
  /ivr/pay/getCustomerAccountDetail:
    post:
      tags:
      - Mobills IVR
      summary: Get Customer Account Detail
      description: 'If the credit balance flag is false, then this endpoint initiates a payment for the IVR and returns the customer''s details. If it''s true, then it returns the customer''s name along with the available credit balance in the account.


        ## Request


        | Property | Description |

        | ------------------------- | ------------------------------------------------------------------------|

        | CustomerARCode | The account code used for Accounts Receivable. (AMCS will provide the account ARCode) |

        | Channel | Channel can be only MOBILL OR IVR. |

        | Amount | Amount that customer wants to make a payment. |

        | CreditBalance | The credit balance flag can be true or false. |


        ## Response


        | Property | Description |

        | ------------------------- | ------------------------------------------------------------------------|

        | CustomerId | The account code used for Accounts Receivable. (AMCS will provide the account ARCode) |

        |CustomerGuid | The GUID associated to the customer. |

        | CustomerName |The customer''s name. |

        | CustomerBalance |The amount associated to the payment.|

        | CustomerCurrency | Customer Currency associated with the Customer account.|

        | CreditBalance |The Credit Balance available balance.|

        | ZipCode |ZipCode associated with the account address |

        | LastPaymentAmount |what was the last payment amount. |

        | LastPaymentDate |When the last payment was made. |

        | TransactionReference |Transaction Reference associated with account.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMCSPayAccountDetailIvrRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCSPayAccountDetailIvrResponse'
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCSPayErrorContentResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCSPayErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMCSPayErrorResponse'
      operationId: postIvrPayGetCustomerAccountDetail
      x-operation-id-source: derived
components:
  schemas:
    AMCSPayErrorResponse:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
          example: error message
          description: The exception message.
        type:
          type:
          - string
          - 'null'
          example: error message
          description: The type of exception thrown.
        stackTrace:
          type:
          - string
          - 'null'
          example: error message
          description: The stack trace of the error encountered.
    AMCSPayAccountDetailIvrResponseCreditBalanceResponse:
      type: object
      properties:
        customerid:
          format: string
          type: string
          example: ACC1001
        customerName:
          type: string
          example: Mark Smith
        creditBalance:
          type:
          - integer
          - 'null'
          example: '200.00'
    AMCSPayAccountDetailIvrRequest:
      type: object
      required:
      - customerARCode
      - channel
      - amount
      properties:
        customerARCode:
          type: string
          example: ACC1007
        channel:
          type: string
          example: MOBILL / IVR
        amount:
          type:
          - integer
          - 'null'
          example: 10
        creditBalance:
          type:
          - boolean
          - 'null'
          example: true
      additionalProperties: false
    AMCSPayInvoiceDetails:
      type: object
      properties:
        invoiceNumber:
          type: string
          example: INV001
        invoiceGUID:
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
          type: string
        invoiceDate:
          type: string
          example: YYYY-MM-DD
        zipCode:
          type:
          - string
          - 'null'
          example: '00501'
        invoiceDueDate:
          type: string
          example: YYYY-MM-DD
        unallocatedAmount:
          type:
          - integer
          - 'null'
          example: '120.95'
        invoiceCurrency:
          type: string
          example: EUR
      additionalProperties: false
    AMCSPayAccountDetailIvrResponse:
      type: object
      properties:
        creditBalanceAsTrue:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCSPayAccountDetailIvrResponseCreditBalanceResponse'
        creditBalanceAsFalse:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AMCSPayAccountDetailIvrResponseCreditBalanceAsFalse'
    AMCSPayMobillsIvrRequest:
      type: object
      required:
      - customerARCode
      - channel
      - amount
      properties:
        customerARCode:
          type: string
          example: ACC1007
        channel:
          type: string
          example: MOBILL / IVR
      additionalProperties: false
    AMCSPayPostBackIvrRequest:
      type: object
      required:
      - transactionReference
      - paymentAmount
      - currency
      - timestamp
      - transactionPaymentType
      - isIVR
      - code
      - description
      - bin
      - last4Digits
      - paymentType
      - holder
      - expiryMonth
      - expiryYear
      - confirmationNumber
      properties:
        transactionReference:
          type: string
          format: uuid
          example: c4521490-c0dd-40e5-94c6-afe90073aa1b
        paymentAmount:
          type: integer
          example: 10.2
        currency:
          type: string
          example: EUR
        timestamp:
          type: string
          format: datetime
          example: 2021-10-21-17:20:30
        transactionPaymentType:
          type: string
          example: Credit Card
        isIVR:
          type: boolean
          example: 'true'
        code:
          type: string
          example: 000.100.112
        description:
          type: string
          example: Request successfully processed in 'Merchant In Connect
        bin:
          type: string
          example: '545454'
        last4Digits:
          type: string
          example: '5454'
        paymentType:
          type: string
          example: DB
        holder:
          type: string
          example: SK_Test
        expiryMonth:
          type: string
          example: '06'
        expiryYear:
          type: string
          example: '2034'
        confirmationNumber:
          type: string
          format: uuid
          example: c4521490-c0dd-40e5-94c6-afe90073aa1b
      additionalProperties: false
    AMCSPayIvrResponse:
      type: object
      example: Success
    AMCSPayErrorContentResponse:
      type:
      - string
      - 'null'
    AMCSPayAccountDetailIvrResponseCreditBalanceAsFalse:
      type: object
      properties:
        customerid:
          format: uuid
          type: string
          example: ACC1001
        customerGuid:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        customerName:
          type: string
          example: Mark Smith
        customerBalance:
          type:
          - integer
          - 'null'
          example: '120.95'
        customerCurrency:
          type: string
          example: EUR
        creditBalance:
          type:
          - integer
          - 'null'
          example: '200.00'
        zipCode:
          type:
          - string
          - 'null'
          example: '00501'
        lastPaymentAmount:
          type:
          - string
          - 'null'
          example: '155.50'
        lastPaymentDate:
          type:
          - string
          - 'null'
          example: YYYY-MM-DD
        transactionReference:
          type:
          - string
          - 'null'
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
    AMCSPayMobillsIvrResponse:
      type: object
      properties:
        customerGuid:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        customerName:
          type: string
          example: Mark Smith
        customerBalance:
          type:
          - integer
          - 'null'
          example: '120.95'
        customerCurrency:
          type: string
          example: EUR
        invoiceDetails:
          type: object
          $ref: '#/components/schemas/AMCSPayInvoiceDetails'
        transactionReference:
          type:
          - string
          - 'null'
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
        zipCode:
          type:
          - string
          - 'null'
          example: '00501'
        dueDate:
          type:
          - string
          - 'null'
          example: YYYY-MM-DD
        invoiceDate:
          type:
          - string
          - 'null'
          example: YYYY-MM-DD
        lastPaymentDate:
          type:
          - string
          - 'null'
          example: YYYY-MM-DD
        lastPaymentAmount:
          type:
          - string
          - 'null'
          example: '155.50'
        makePaymentLink:
          format: url
          type:
          - string
          - 'null'
          example: https://localhost/paybylink?key=092159d8-9e57-41a5-af6c-745bd45ff2f7
        isActive:
          type: boolean
          example: 'true'
        mobillsEnrollment:
          type: boolean
          example: 'true'
        guid:
          format: uuid
          type:
          - string
          - 'null'
          example: 00000000-0000-0000-0000-000000000000
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: Platform.PAY.SessionToken
