openapi: 3.2.0
info:
  title: Core SSO API
  version: core
tags:
- name: SSO
paths:
  /services/api/sso/login:
    get:
      tags:
      - SSO
      parameters:
      - name: return
        in: query
        schema:
          type: string
      - name: accessDeniedUrl
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
      summary: Get services api sso login
      x-summary-source: derived
      operationId: getServicesApiSsoLogin
      x-operation-id-source: derived
  /services/api/sso/logout:
    get:
      tags:
      - SSO
      responses:
        '200':
          description: Success
      summary: Get services api sso logout
      x-summary-source: derived
      operationId: getServicesApiSsoLogout
      x-operation-id-source: derived
