openapi: 3.0.1
info:
  title: Core AccessGroup IntegratedHeader API
  version: core
tags:
- name: IntegratedHeader
paths:
  /services/api/verifyErp:
    get:
      tags:
      - IntegratedHeader
      responses:
        '200':
          description: Success
