openapi: 3.2.0
info:
  title: Core Plugin Metadata Registry API
  version: core
tags:
- name: PluginMetadataRegistry
paths:
  /metadata/{type}.xml:
    get:
      tags:
      - PluginMetadataRegistry
      parameters:
      - name: type
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
      summary: Get metadata {type} xml
      x-summary-source: derived
      operationId: getMetadata{type}Xml
      x-operation-id-source: derived
